++++++++++++++++++++++++++++++++++++++++
Dungeon Crawl Stone Soupマニュアル
++++++++++++++++++++++++++++++++++++++++

.. contents::
   :depth: 5

########################################
マニュアル
########################################

****************************************
A. 概要
****************************************

Crawlは、ローグ、ハック、モリアなどの同様のゲームの壮大な伝統を継承した楽しい
ゲームです。目的は、地下の洞窟複合施設の奥深くに移動し、多くの恐ろしく恐ろしい
生き物によって守られているゾットのオーブを回収することです。

これまでにCrawl (または同様のゲーム)をプレイしたことがない場合は、スタートメニ
ューからチュートリアルを選択してください。このチュートリアルでは、5つの簡単な
レッスンでインターフェイスについて説明します。コントロールに慣れたら、ヒントモ
ードを使用していくつかのゲームをプレイするとよいでしょう。

Crawlをプレイするための詳細な手順は次のとおりです。このマニュアルを簡略化する
ために、標準のディストリビューションを使用しており、デフォルトのオプションを変
更していないことを前提としています。マニュアル全体を読みたくない、重要なポイン
トの短い概要を知りたい場合は、クイックスタートガイドファイル(quickstart.txt)を
確認して、遊びながら学習してください。

Crawlのプレイ中にヘルプメニューで'?'を押して、これらのドキュメントを読むことも
できます。ゲームプレイとデザインに関するよくある質問のリストには、ゲーム内で'?
Q'を押すとアクセスできます。

Dungeon Crawlは厳密にはシングルプレイヤーゲームですが、サーバーを介して他のプ
レイヤーと対話することができます。サーバーに接続すると、いくつかの興味深いオプ
ションが開きます。

あなたはできる：

- 他のプレイヤーを観察し、コミュニケーションをとることもできます
- 自分の過去のゲームや他の人のゲームを表示する
- 他のプレイヤーのゴーストと戦う
- 共通のスコアリストを使用して競う
- 毎年恒例のトーナメントに参加する
- 最新の開発バージョンをプレイする

利用可能なサーバーの完全なリストとそれらへの接続方法に関する情報は、
http://crawl.develz.org/wordpress/howto でご覧いただけます。

サーバーは通常は常に稼働していますが、保証はありません。

irc.freenode.netの##Crawlには、Crawl専用の活発なIRCチャネルもあります。助けを
求めることができ、サーバー上でプレイしている場合には、あなたのゲームを見てヒン
トをくれる人が常にいます。

****************************************
B. 起動画面
****************************************

Crawlスタート画面では、さまざまなゲームモード、保存されているゲームのリスト(存
在する場合)が表示され、キャラクターの名前を入力するよう求められます。カーソル'
up'および'down'矢印キーを使用して、ゲームモードと保存されたゲームに移動できま
す。

ゲームモードは次のとおりです。

Dungeon Crawl
  Crawlの標準ゲームを開始します。

Dungeon Crawlのチュートリアル
  いくつかの専門的なチュートリアルの1つを開始して、遊び方を学びましょう。

Dungeon Crawlのヒントモード
  プレイ中にヘルプを提供するように変更されたCrawlの標準ゲームを開始します。

ダンジョンスプリント
  Crawlのいくつかのシングルマップチャレンジモードゲームの1つを開始します。

ゾット・ディフェンス
  Crawlのいくつかの「タワーディフェンス」スタイルゲームの1つを開始します。

説明書
  現在読んでいる説明ヘルプテキストを表示します。

アリーナ
  指定された2つの戦闘グループ間で自動戦闘モードを開始します。

ハイスコア
  以前にプレイしたゲームのスコアをスコアの降順に並べて表示します。

名前を入力した直後に'enter'を押すと、標準のDungeon Crawlモードが選択され、種族
と職業を選択するように求められます。名前は一意です。保存されたゲームのリストか
ら名前を入力すると、その保存されたゲームが続行されます。名前を入力する代わりに
ゲームモードを選択すると、最終的に名前の入力を求められる場合があります。

種族と職業をどちらかの順序で選択することも、ゲームに決定させたい場合は任意の組
み合わせをランダム化することもできます。両方がランダムな場合は、ゲームの開始前
に選択した組み合わせを確認するよう求められます。

種族の選択は、いくつかの重要な特性、特にさまざまなスキルを学習する速度に影響し
ます。これは非常に重要であり、多数の種族を明確に区別するのに役立ちます。次の要
素は種族に依存します。

選考科目：

- 各レベルで獲得できるヒットポイントの量
- スキルの進歩率
- 初期のプライマリ属性(これは職業にも依存します)
- さまざまな特殊能力、力、制限

マイナー：

- あなたのレベル上昇率
- いくつかの主な属性に時折ボーナスポイントが追加されます
- 各レベルで獲得できるMPの量
- 敵対的な魔法に対する生来の抵抗力
- 初期装備(これも職業によって異なります)

.. note::
   人間は他のすべての種族と比較される平均です。

文字職業の選択は、Crawlの種族の選択よりも決定的ではありません。基本的に、職業
は、ダンジョンに入る前にキャラクターが何を学習したか(つまり、開始スキル)を決定
し、開始時の装備を決定するのにも役立ちます。

種族ごとに、異なる職業セット(白)が推奨されることがわかります。ほぼすべての種族
と任意の職業を自由に選択できますが(唯一の制限は、一部の種族が特定の神を崇拝す
ることを許可されていない宗教的な職業、または特定の種族が初期装備を完全に使用で
きない職業です)、推奨される組み合わせを見ると、弱点と大まかな印象が得られるは
ずです。さまざまな種族の強み。

一部の職業では、ゲームを開始する前に開始武器を選択する必要があります。

新しいキャラクターを開始(または古いキャラクターをロード)し、大まかな印象を知り
たい場合は、次のコマンドを使用して調べることができます。

A
  異常な速度や摂食行動などの特殊性を示す

m
  スキルが表示され、必要に応じてトレーニングを無効化(または集中)できます。

i
  装備とアイテムのリスト

^
  宗教を始めた場合に備えて、あなたの神に関する情報を表示します

%
  簡潔ではありますが、ギアとほとんどの属性の概要を示します

Ctrl-O
  これまでに発見したダンジョンの一部の概要を示します

****************************************
C. 能力値
****************************************

プレイマップの右側にある統計エリアには多くの情報が表示されます。これはキャラク
ターの名前とタイトル(キャラクターの最高位スキルによって決まります)で始まり、そ
の後に種族をリストする行が続きます。キャラクターが神を崇拝している場合、その神
の名前も信仰値のインジケーターとともに2行目にリストされます。これら2行の下には
多くの数字が続きます。これらはキャラクターのさまざまな側面を説明します。

健康
  生命力の尺度。ヒットポイントと同義で、HPと略されることもあります。健康状態が
  ゼロ以下になると死亡します（ただし、他の方法でも死ぬ可能性があります）。メイ
  ン画面には、現在と最大のヒットポイントの両方が表示されます。通常、ヒットポイ
  ントは時間をかけてゆっくりと回復します。 '5'またはShift-Num-5を押すと、より
  長い時間待つことができます。

魔法
  魔法またはその他の固有の力の尺度。これは主に呪文詠唱に使用されますが、他の多
  くの特殊能力の呼び出しや呼び出しにも使用されることがあります。これらはヒット
  ポイントと同じ方法で表示されます。これらがゼロになっても何も悪いことは起こり
  ませんが、もちろん、呪文をキャストできなくなります。これらも休むと回復します。
  外部デバイスを使用せずに50 MPを超えるのは困難です。

次に防御です。それらすべてにとって、多ければ多いほど良いのです。

アーマークラス
  略称は「AC」。何かがあなたを傷つけたとき、あなたのACはあなたが受けるダメージ
  の量を減らします。

回避力
  略称は「EV」。これにより、不快なものによる攻撃を避けることができます(ただし、
  攻撃を受けた場合に受けるダメージの量が軽減されるわけではありません)。

盾
  略称は「SH」。この数値は、盾(存在する場合)が攻撃のブロックにどれだけ優れてい
  るかを示す尺度です。

キャラクターの主な属性は、腕力、知力、および器用さです。

腕力
  略称は「ストラ」。近接武器と遠距離武器の有効性が向上します。重い鎧や盾を効果
  的に使用する能力に影響します。

知力
  略称は「イント」。呪文をどれだけうまくキャストできるか、および呪文詠唱がどれ
  だけの栄養を摂取するかに影響します。

器用さ
  略称は「デックス」。近接武器と遠距離武器の有効性が若干向上します。自分に向け
  られた攻撃を回避する能力、シールドの一般的な有効性、ステルス性、および気づい
  ていない敵を刺すときの有効性に大きく影響します。

属性はレベルの上昇により永続的に増加しますが、変異から、または特定のアーティフ
ァクトまたは能力の使用中に一時的に増加または減少する場合があります。

何らかの理由でいずれかの属性がゼロになると、非常に不快な副作用が発生し、大幅に
速度が低下し、ステータスがさらに消耗するとダメージを受けるほか、ステータス固有
のマイナス効果も発生します。これらの効果は属性が回復した後もしばらく持続します。

レベル3、6、9などに到達すると、上げる属性を選択できます。ほとんどの種族はいく
つかのレベルで追加の属性を獲得し、増加する頻度と属性は種族によって決定されます。

次に表示される数値は経験値と(ダンジョン)レベルです。

経験レベル
  略称は「XL」。開始文字は経験レベル1です。可能な最高レベルは27です。レベルを
  獲得すると、追加のヒットとMPが得られ、呪文スロットと、場合によってはプライマ
  リ属性が付与されます。

場所
  これは、現在いるブランチとブランチ内のレベルを示します。開始分岐はダンジョン
  と呼ばれ、新しいキャラクターの場所情報は「ダンジョン:1」となります。

ターンごとにそれほど重要ではないため、メインの統計領域にはリストされていない追
加の統計がいくつかあります。ただし、'@'または'%'コマンドを使用して簡単に確認で
きます。

魔法耐性
  あなたに向けられたエンチャントや同様の魔法の効果に抵抗する能力に影響します。
  魔法によって与えられる直接的なダメージには影響せず、より微妙な効果にのみ影響
  します。魔法耐性はキャラクターの種族によって決まる範囲でレベルとともに増加し
  ますが、ダンジョンの奥深くで出会う生き物は呪文を唱えるのが上手で、あなたに影
  響を与える可能性が高くなります。 '@'または'%'を押すと、現在のMRの大まかな情
  報を取得できます。

ステルス
  高いステルス性により、キャラクターは発見されずにダンジョンを移動できます。そ
  れは、種族、器用さ、ステルススキル、およびボディアーマーの邪魔になる影響を受
  けます。現在のステルスレベルは、'@'または'%'を押しても確認できます。

一時的にあなたに降りかかる可能性のある病気や魔法はたくさんあります。これらは経
験値ラインの下の統計領域に記載されています。 PoisやHungryなど、その多くは一目
瞭然です。ただし、その他の多くは微妙な場合があり、説明付きの完全なリストは付録
`5. ステータス表記一覧`_に記載されています。

視界内のモンスターは、特別なパネル(モンスターリスト)にリストされます。独身のモ
ンスターは、健康状態の指標をカラーボックスの形で取得し、享受している影響や苦し
んでいる影響についても知ることができます。ターゲットモード内では、モンスターリ
ストを使用して単一のモンスターを直接ターゲットにすることができます。これを切り
替えるには、'Ctrl-L'を使用します。

場合によっては、キャラクターが特別な能力を使用できるようになります。ナーガの毒
を吐き出す能力や、指輪によって透明になる魔法の力。これらには、'a'コマンドを通
じてアクセスします。

****************************************
D. ダンジョンの探索
****************************************

動き
========================================

テンキー (Numlockのオンとオフの両方を試してください)または「Rogue」キー (
hjklyubn)を使用して、キャラクターを歩き回らせることができます。これが遅すぎる
場合は、Shiftキーと方向キーを押してキャラクターを繰り返し歩かせることができま
す。または、'/'を押してから方向を押します。敵対的なモンスターが画面に表示され
る、何らかの理由でメッセージウィンドウにメッセージが送信される、キーを押す、ま
たは通常の床以外のものを踏もうとしているが、それが長い散歩の最初の動きではない
など、さまざまな出来事が起こるまでその方向に歩きます。これは、方向キーを数回押
すことと機能的に同等であることに注意してください。

長距離を移動するための別の便利な方法については、以下の自動移動と探索のセクショ
ンで説明します。

休憩中
========================================

'5'を押すと、100ターン、またはヒットポイントか魔法が完全に戻るまでのどちらか早
い方の間休憩します。 '.'または's'を押すと1ターンだけ休憩できます。

モンスターが表示されるか、中断されると、休憩は停止します。

周囲を調べる
========================================

表示ウィンドウの色が付いている部分(中心にあなたを表す「@」が付いています)が、
あなたの周囲に見えるものです。周囲の濃い灰色は、訪問したことがあるレベルの部分
ですが、現在は見ることができません。 'x'コマンドを使用すると、カーソルを移動し
てダンジョンのさまざまな機能の説明を取得できます。カーソルがモンスターまたは機
能の上にあるときに'v'と入力すると、そのモンスターの短い説明と、さまざまな長所、
弱点、免疫、および呪文またはそれが持つ能力の短いリストが表示されます。これは通
常、これまでに経験したことのないモンスターで役立ちます。 「'X'」と入力すると、
レベル全体のマップ(すでに行った場所を示す)を取得できます。

'x'モードと'X'モードの両方で、'?'を押して周囲を見回すと、使用可能なコマンドの
完全なセットを確認できます。

階段と門
========================================

'>'キーまたは'<'キーを押して、「>」 (下)および「<」 (上)として表示される階段を
使用してレベル間を移動できます。レベルを変更すると、隣接するほとんどのモンスタ
ーが追従することを知っておくことが重要です。これは、敵対味方のモンスターの両方
に当てはまります。注目すべき例外は、ゾンビ(および階段を適切に操作できないほど
愚かなその他の思慮のないアンデッド)と幽霊(自分たちのレベルに属していると感じて
いる)です。

レベル1の上り階段を登ると、ダンジョンから永久に離れることになります。魔法のゾ
ットのオーブを持っている場合は、これを行うことでゲームに勝ちます。そうしないと
ゲームが終了し、負けになります。

Crawlのダンジョンには、開始ダンジョン以外にも多くの分岐があります。それらはす
べてテーマがあり、何らかの特別な種類の対戦相手をホストします。特定のブランチを
訪問することは必須ではありませんが、いくつかのブランチを探索する必要があります。
ゾットの領域(オーブがある場所)に進むことができるのは、ゾットの魔法のルーンを少
なくとも3つ持っている冒険者だけです。いくつかの枝の底にはそのようなルーン文字
が含まれています。

時々、アーチ道(「\\」または実際のアーチとして表示されます)が見つかることがあり
ます。これらは、お店、神話の迷宮、地獄などの特別な場所につながります。 '<'また
は'>'と入力して入力できます。いくつかのポータルでは、'<'と'>'の1つだけを受け入
れます。

ドアとトラップ
========================================

ドアは通常、中に入るだけで開くことができます(これを無効にするオプションがあり
ます)。それ以外の場合は、'O'コマンドを使用してこれを行うこともできます。これら
は'C'コマンドで閉じることができます。 Ctrlキーを押しながら方向キーを押すか、'*
'キーを押して方向キーを押すと、ドアも開閉します。

指定されたスペースにドアがない場合、Ctrl-directionと'*'方向の両方が、そこに立
っている可能性のあるモンスターを攻撃しようとします(これが、味方のクリーチャー
を白兵戦で攻撃する唯一の方法です)。明らかに何もない場合でも、目に見えない何か
が潜んでいる場合に備えて、攻撃することになります。

ダンジョンのあちこちには、危険で刺激的なさまざまな罠が隠されています。トラップ
は、発見されるまでは通常の床のように見えることがあります。

ショップ
========================================

お店に行くと、店主が在庫を見せてもらい、何を買うかを選ぶことができます。残念な
がら、店主は全員ギルド・オブ・ダンジョン・プロキュアラーズと独占契約を結んでい
るため、ギルド以外の労働力を使って在庫を入手することはできないため、店で何かを
売ることはできません。 （でも、そもそも、どんな店主が評判の悪い冒険者から盗品
を買うだろうか？）

1つ以上のアイテムを購入するには、ショップメニューでアイテムの文字を押してアイ
テムを選択し、Enterキーを押して購入します。 '!'を押してから商品の文字を押すと、
購入前に商品を調べることができます。

ダンジョン内のお店を見失った場合は、ダンジョン概要で見つけたすべての店のリスト
を取得できます('Ctrl-O'を使用)。

スタッシュ検索も使用できます。'Ctrl-F'を押して「ショップ」を検索すると、すべて
のストアがリストされます。隠し場所検索メニューを使用すると、特定のショップにす
ばやく移動できます。お店の在庫を知りたいだけの場合は、わざわざお店まで行かなく
ても、検索メニューからお店の在庫を調べることもできます。

一部の店は、出所不明の品物を通常かなりの割引価格で販売する骨董品店です。ダンジ
ョン概要画面では、これらが黄色のグリフで表示されます。

特に興味深い商品のためにゴールドが不足している場合は、それを買い物リストに追加
できます。最終的にそのリストにあるアイテムを購入するのに十分なゴールドを集めた
ときに、ゲームが中断されます。 '$'を使用すると、ゲーム内の買い物リストを読み取
ることができます。

自動移動と探索
========================================

Crawlには充実した自動移動システムがあります。'G' (または'Ctrl-G')を押すと任意
の階層を選択でき、目的地までの最短経路を自動で移動します。レベルマップ('X')上
でも、目的地へカーソルを動かしてEnterキーを押せば自動移動できます。目的地の選
択にはショートカットもあり、たとえば'<'と'>'で階段をすばやく選べます。

自動移動が中断された場合、Crawlは前の目的地を記憶します。もう一度'G'または'
Ctrl-G'を押してEnterキーを押すと、そのマスにカーソルが置かれます。レベルマッ
プモードのすべてのコマンドとショートカットについては付録
`4. コマンド詳細一覧`_を参照するか、ゲーム内で'G?'または'X?'を押して
ください。

自動移動は探索にも使えます。'o'を押すと、最も近い未探索領域へ移動します。この
処理は最短ターン数を目指すものではありません。手動ならターンを節約できますが、
自動探索なら実際の操作時間を節約できます。

隠し場所と検索
========================================

アイテムは52個しか持ち運べないので、時々 ('d'コマンドでドロップして)アイテムを
隠しておきたい場合があります。隠し場所で何かを検索したい場合は、検索コマンド'
Ctrl-F'を使用してこれを行うことができます。パーサーは正規表現も受け入れますが、
ほとんどの場合必要なのは'mutation'、'heal wounds'などの文字列だけです。検索に
一致するアイテムが存在する(または存在した)すべての場所のリストが表示されます。
その後、そこへ自動移動したり、アイテムの山を調べたりできます。「検索」コマン
ドはショップの在庫も検索します。さらに、'long blades'のようなスキル(ロングブレ
ードスキルを訓練するすべての武器が検索されます)や、'shop'、'altar'、'portal'、
'artefact'、'teleport trap'などの一般的な用語を検索することもできます。を押す
と、検索に関するヘルプが表示されます。プロンプトで'?'。

目標
========================================

あなたの目標は、世界の地下深くに保管されているゾットのオーブを見つけることです。
オーブは古代の信じられないほど強力なアーティファクトであり、伝説によれば、恐ろ
しいダンジョンからオーブを取り出す勇気のある人には素晴らしいことが約束されてい
ます。それを太陽の光の中に持ち込んだ者には不死、さらには神性が与えられると言う
人もいます。多くのアンデッドの生き物は、それが彼らを生き返らせることを期待して
それを探しています。しかし、その後、何でも信じる人もいます。幸運を！

さらに詳しいヘルプ
========================================

Crawl's help menu, press 'にアクセスするには?'。すべてのコマンドのリストを取得
するには、もう一度'?'を押します。コマンドの別の、より詳細な説明は、このテキス
トの付録`4. コマンド詳細一覧`_にも記載されています。このマニュアルを
含め、他のさまざまなヘルプテキストも利用できます。 ':'を押して、そこからログブ
ックを読むこともできます。いくつかのコマンドには独自のヘルプ画面があることに注
意してください。ターゲティング('f')、レベルマップ('X')、自動移動('G'または
'Ctrl-G')、検索('Ctrl-F')などです。入力を求められた場合は、もう一度'?'を押します。

標準のキーセットが気に入らない場合(一部のキーが正しく動作しないため、または必
要な入力の量を減らしたいため)、キーマップとマクロを使用できます。 docs/ディレ
クトリ内のmacros_guide.txtを参照するか、ゲーム内のヘルプメニューから読んでくだ
さい。

****************************************
E. 経験レベルおよびスキル
****************************************

モンスターを倒すと、経験値(XP)を獲得します。味方のクリーチャーがモンスターの殺
害に参加した場合、受け取るXPは少なくなります。十分なXPを獲得すると、経験レベル
を獲得し、キャラクターがより強力になります。レベルが上がるにつれて、キャラクタ
ーはヒットポイント、MP、および呪文レベルをさらに獲得します。

さらに、得た経験はスキルのトレーニングに使用されます。これらのスキルは、野心的
な冒険家がダンジョンで必要とするあらゆる分野の努力の熟練度を表します。それらは、
さまざまな武器スキル(近接戦闘と遠距離戦闘の両方)から多くの魔法のスキル、および
回避やステルスなどの追加のアクティビティにまで及びます。 Crawlに存在するすべて
のスキルの詳細な説明については、付録`3. スキル一覧`_を参照してください。キ
ャラクターがスキルを学習する容易さは、種族のみに依存します。これらの適性は、種
族のリストで示唆されています(付録`1. 種族一覧`_を参照)。興味
がある方は、完全なテーブルをaptitudes.txtで確認できます(プレイ中のヘルプ画面か
らも'?%'経由で)。ただし、勝つためにわざわざ数字を気にする必要はありません。

'm'キーを押すと、キャラクターのスキルが表示されます。スキルのレベルが高いほど、
より優れています。すべてのキャラクターは、すでにトレーニング済みのいくつかのス
キル(基本的に職業に依存します)から始まり、存在しないものは最初から学習する必要
があります。各スキルは最大27まで可能です。

スキル画面では、どのスキルをどの速度で実行するかを変更できます。新しいプレイヤ
ーへの注意:通常、スキルの選択を微調整する必要はありません。

スキルの選択を変更したい場合の方法は次のとおりです。

スキルを練習に割り当てるには2つの方法があります。1つは自動モードで、最近使用し
たスキルに経験値を投入します。もう1つは手動モードで、トレーニングするスキルを
具体的に選択します。キャラクタースキル画面('m')で'/'を押すと、モードを切り替え
ることができます。スキルセットを微調整したい場合は、その画面のヘルプテキストも
必ずお読みください。

特定のスキルを練習しないことも、スキル画面で1回または2回選択して集中することも
できます。

ダークグレーのスキルはトレーニングされないため、スキルは静的なままとなり、経験
値を増加させることはありません。結果として、より多くの経験値が他のスキルに費や
されることになります(したがって、より早く増加します)。すべてのスキルの選択を解
除することはできないことに注意してください。少なくとも1つのスキルをアクティブ
に実行する必要があります。

ハイライト表示されたスキルに焦点が当てられ、利用可能な経験のより高い割合が使用
されます。好きなだけスキルを強調表示できますが、トレーニングされているすべての
スキルを強調表示しても、実質的な効果はありません。

場合によっては、この分野で迅速に進歩できるスキルのマニュアルを見つけることもあ
ります。所持していると、一定時間、指定されたスキルの練習に使用した経験値の効果
が通常の2倍になります。

****************************************
F. モンスター
****************************************

Crawlの洞窟では、多種多様な生き物が見つかります。そのほとんどはアルファベット
の大文字または小文字で表示されます。彼らの多くはあなたを食べたいと思っています。
彼らのこれを阻止するには、通常、彼らと戦う必要があります。モンスターを攻撃する
には、その隣に立ってその方向に移動します。これにより、使用した武器で攻撃するこ
とができます。もちろん、一部のモンスターは、あまりにも厄介なので倒すことができ
ません。多くの場合、慎重さが勇気のより良い部分であることがわかります。卑劣なキ
ャラクターは、自分の好みに合わせて出会いを選ぶことが知られています。

モンスターを強制終了するために使用できる、危険性の低い方法が他にもいくつかあり
ます。ハンターや同様の方向性のキャラクターは、無謀な攻撃よりも遠隔戦闘を好みま
す。ランチャーを使用する場合、'f'および'F'コマンドは適切なミサイルを発射します。
詳細については、アイテムの章のターゲティングに関するセクションを参照してくださ
い。同様に、多くのマジシャンは安全な距離から呪文を使用することを好みます。 'z'
コマンドを使用して、以前に記憶した呪文をキャストできます。もう一度、「ターゲテ
ィング」セクションを参照してください。

一部のモンスターはフレンドリーです。フレンドリーなモンスターがあなたを追いかけ、
あなたの代わりに戦ってくれます(ただし、彼らがキルすると通常の経験値の一部を獲
得するため、得られる経験値は少なくなります)。 't'キーを使用して味方に命令する
ことができます。これにより、叫び声を上げて味方を引き寄せたり、誰を攻撃するかを
指示したり、その場に留まるか再び追いかけるように指示したりすることができます。
何らかの理由でそうしたい場合は、範囲内のすべてのモンスターの注意を引くために叫
ぶこともできます。

一部の特別なモンスターはユニークです。その人には名前と性格があるので、その人を
識別することができます。これらの多くは、ダンジョンからあなたを追い出すための非
常に厄介なアイデアを思いつきます。特に初めて会う人には、細心の注意を払って接し
てください。

さらに珍しい障害物としては、彫像があります。無害な花崗岩の彫像(今でも興味深い
ものを意味することが多い)から、本当に恐ろしい彫像まで、さまざまな彫像が登場し
ます。そのような彫像を見かけたら注意してください。

Crawlをプレイするときは、さまざまなモンスタータイプの感覚を養いたくなることは
間違いありません。たとえば、モンスターの中には、食べられる死体を残すものもあれ
ば、残さないものもあります。同様に、遠距離または魔法の攻撃者は、近接戦闘機とは
異なる種類の脅威となるでしょう。過去の死から学び、どのモンスターが最も問題を引
き起こすかを思い出してください。特定のモンスターが問題を引き起こしている場合は、
今後の遭遇に備えて戦術を変更してみてください。

'x' (検査)コマンドを使用し、カーソルを問題のモンスターの上に移動し、'v'を押し
てモンスターの詳細を表示することで、モンスターに関する情報を取得できます。また
は、'?/m'を使用して、名前またはシンボルでモンスターを検索します。詳細画面には
以下が表示されます。

- モンスターの名前と説明。

- それを示すバー:

  * AC:アーマークラス;ほとんどのダメージをどれだけ無視できるか

  * EV:回避力;攻撃をどれだけ回避できるか

  * MR:魔法耐性。ほとんどのヘックスや同様のエンチャントにどれだけ耐えられるか。

-難易度、速度（平均速度と異なる場合）、サイズ、
  耐性と特殊攻撃。

-呪文と特殊能力。モンスター呪文と能力は
  5つのタイプ:

  * 特殊能力は生まれつきの、魔法ではない効果です。

  * 魔法の能力は生まれつきの魔法の効果です。彼らは反魔法の影響を受けます。

  * 悪魔と天使の能力は魔法の能力に似ています。

  * 神聖な能力は、モンスターの神に魔法の効果を求めます。それらは沈黙によって妨
    げられますが、反魔法の影響を受けません。

  * 呪文は記憶した魔法の言葉を使って唱えられます。どちらも沈黙によって妨げられ、
    反魔法の影響を受けます。

****************************************
G. アイテム
****************************************

Crawlのダンジョンでは、さまざまな種類の通常アイテムや魔法のアイテムを見つけて
使用できます。それらの中には便利なものもあれば、厄介なものもあり、大きな力を与
えるものもありますが、代償が伴います。一部のアイテムはユニークです。これらには
興味深い特性があり、しばらくの間あなたの人生をかなり奇妙なものにする可能性があ
ります。これらはすべていくつかのクラスのアイテムに分類され、それぞれが異なる方
法で使用されます。以下は、冒険の過程で見つかる可能性のあるもの、それらがどのよ
うに表示されるか、そしてそれらを使用するためのコマンドの一般的なリストです。

  =======  ==============  ================================================
  )        武器            ('w'で装備)
  (        飛び道具        ('f'で発射)
  [        防具            ('W'で装備し、'T'で外す)
  %        食料            ('e'で食べ、死体は'c'で解体)
  ?        巻物            ('r'で読む)
  !        ポーション      ('q'で飲む)
  /        ワンド          ('V'で発動)
  =        指輪            ('P'で装備し、'R'で外す)
  "        護符            ('P'で装備し、'R'で外す)
  \\ or |  杖、ロッド      (杖は'w'で装備し、ロッドは'v'で発動)
  \+ or :  魔法書          ('r'で読み、'M'で記憶し、'z'で唱える)
  }        その他          (インベントリから'V'で発動)
  $        金貨            ('g'で拾う)
  =======  ==============  ================================================

アイテム管理にはいくつかの一般的なキーがあります。

d
  アイテムをドロップします。スタック(矢印など)から一部のアイテムのみをドロップ
  したい場合は、'd'を押し、続いて数字を押し、次にアイテムのスロットキーを押し
  ます。

g
  地面からアイテムを拾います(カンマキー ','も使用)

=
  アイテムスロットの再割り当て(呪文スロットとアビリティでも機能します)

i
  インベントリの表示-アイテムのキーを押すと追加情報が表示されます

{
  項目の記入(付録`6. アイテムへの銘の効果`_を参照)

\\
  すでに発見されたアイテムのチェックリスト

アイテムの使用方法
========================================

'g'etまたは',' (カンマ)コマンドでアイテムを選択し、'd'ropコマンドでドロップし
ます。 「どのアイテムをドロップしますか？」のようなプロンプトが表示された場合、
アイテムの文字の前に数字を入力すると、その数量のアイテムがドロップされます（拾
うときと同様）。スタックの一部だけを取得したい場合、および広場に数種類のアイテ
ムがある場合も同様です(リストに表示されるように)。矢のスタックが1つしかなく、
その一部だけを取り出したい場合は、';'コマンドを使用します。 1つのマスからアイ
テムを拾うにはちょうど1ターンかかることに注意してください。ただし、複数のアイ
テムを一度にドロップすると、より多くのターンがかかります。

'i'と入力すると、在庫(何を持っているか)が表示されます。 「どのアイテムを投げま
すか?」のようなプロンプトが表示されると、通常、利用可能なすべてのオプションの
リストが表示されます。珍しいものを使いたい場合は、'*'を押してください。インベ
ントリ画面に「-more-」と表示されている場合、アイテムの別のページがあることを示
すために、スペースまたはEnterキーを押して次のページを表示する代わりに、表示さ
れていない場合でも、必要なアイテムの文字を入力できます。

一度に最大52個のアイテムを持ち運ぶことができ、アイテムスロットの使用状況がイン
ベントリ画面の上部に表示されます。

調整コマンド('='キー)を使用して、所有物に割り当てられている文字を変更できます。
このコマンドは呪文や能力文字の変更にも使用できます。

一部のアイテムには粘着性が付与されている場合があり、その場合、使用すると体に溶
けてしまいます。このようなアイテムには通常、何らかの不利な点が伴います。武器や
防具は損傷したり、マイナスの魔法がかけられたりする可能性があり、指輪はあらゆる
種類の不快な影響を与える可能性があります。運が良ければ、これらの呪いを取り除く
魔法が見つかるかもしれません。

巻物、ポーション、その他の種類のアイテムにはそれぞれラベルや色などの特徴があり、
機能に基づいて区別できます。ただし、これらの特性はゲームごとに変化するため、あ
るゲームではすべての治癒ポーションが黄色である一方で、別のゲームではすべてが紫
色で泡立っている場合もあります。そのようなアイテムの機能を一度発見すると、現在
のゲームの残りの間、それを覚えておくことになります。 '\\'キーを使用してアイテ
ムの検出にアクセスできます。

アイテムの機能の説明を取得するには、インベントリ('i')を表示し、そのアイテムの
文字を押します。さまざまな種類の鎧や武器を比較するときにこれを試してください。
ただし、未確認のアイテムを調べることで多くの情報を期待しないでください。

もう1つの便利なコマンドは、項目にコメントを書き込むことができる'{'キーです。 '
i'でインベントリを確認しているときに、アイテムの文字を押すだけでアイテムを刻印
することもできます。詳細およびこのプロセスを自動化する方法については、付録
`6. アイテムへの銘の効果`_を確認してください。

)武器
========================================

これらはかなり重要です。ダンジョンでは、小さくて素早い短剣から、巨大で扱いにく
い戦斧や棒武器まで、さまざまな武器が見つかります。武器の種類ごとに与えるダメー
ジの量、ターゲットに命中する確率、スイングにかかる時間も異なります。ショートブ
レード、ロングブレード、斧など、いくつかの武器スキル('m'を押すとトレーニングし
ているもののリストが表示されます)があります。これらのスキルは、ダメージ、命中
精度、速度(ある点まで)に影響します。素手格闘も同様です。

武器には魔法をかけることができます。初めてそれらを使用するか、その他の方法でそ
れらを識別するとき、あなたはそれらがエンチャントされていないバージョンよりもど
れほど効果的であるかを示す値を明らかにします。エンチャントされていない武器は単
純に'+0'です。一部の武器には特別な魔法の効果があり、弱い敵に対して非常に効果的
です。

'w'コマンドを使用して武器を使用できます。これは非常に素早いアクションです。何
らかの理由で素手で使用したい場合は、「'w'」と入力し、その後にハイフンを入力し
ます('-')。武器以外の武器を使用すると便利な場合があることに注意してください。

' (アポストロフィ)キーは、スロットaのアイテムを自動的に使用するショートカット
です。アイテムaが使用されている場合、'により、可能であれば、代わりにアイテムb
を使用するようになります。文字aを主な武器に割り当て、bを弓や時々しか使用する必
要がないものに割り当ててみてください。これは単なる入力ショートカットであり、こ
れらのアイテムを通常に使用することと機能的には変わらないことに注意してください。

(ミサイル
========================================

安全な距離からモンスターを狙い撃ちしたい場合は、スリング、弓、またはその他の適
切な発射装置にミサイルが必要になります。ジャベリンなどのいくつかの種類のミサイ
ルは、投げるだけで効果を発揮します。他の種類では、価値のあるダメージを与えるた
めに適切なデバイスを使用する必要があります。衝突すると、ミサイルは破壊される可
能性があります。これが発生する可能性はミサイルの種類によって異なります。

'f'コマンドはミサイルを発射または投げます。発射または投げられるデフォルトのミ
サイル(「矢筒」)は、メイン画面の使用している武器の下に表示されます。震えるアイ
テムは常に、Crawlがあなたが望むものである可能性が最も高いと考えるものです。し
たがって、それは、以前に選択して発射したアイテム('f'の場合)、または直接震えさ
せたアイテム('Q'の場合)、またはfire_orderで最も高いランクにあるインベントリ内
のアイテムのいずれかになります。同様の順序が複数ある場合は、インベントリスロッ
トが最も低いものが選択されます。

選択するアイテムのリストを微調整できる碑文については、付録
`6. アイテムへの銘の効果`_を
参照してください。 options_guide.txtの「ミサイル」セクションも参照してください。

発射インターフェイスでは、'i'で投げるアイテムを手動で選択することもできます。
ただし、適切なランチャーがない場合は、あまり効果的ではない可能性があります。

'('、')'を使用すると、射撃せずに矢筒の矢弾を順に切り替えられます。'Q'を使用す
ると、矢筒に入れるアイテムをリストから選択できます。矢筒に入れずに発射するもの
を選びたい場合は、代わりに'F'を使用してください。

物を撃ったり投げたりするためのインターフェイスは、杖を呼び出したり、特定の呪文
をキャストしたりするためにも使用され、セクションI (ターゲット設定)で詳細に説明
されています。

[鎧
========================================

これもかなり重要です。最も着用されている鎧はアーマークラスを向上させ、ほとんど
の種類の怪我から受けるダメージの量を減少させます。装甲が重ければ重いほど、EV (
回避力)とステルス性を犠牲にして、より多くのAC (アーマークラス)を提供します。重
いタイプの装甲も近接攻撃の精度を妨げ、モンスターを攻撃するのを難しくします。重
い鎧を着ていると、呪文をミスキャストする可能性も高くなりますが、この効果は鎧ス
キルによってわずかに減少します。これらのペナルティは、アーマースキルが高い場合
は小さくなりますが、腕力が低い場合は大きくなります。一方で、ボディアーマーは近
接攻撃に対してある程度のダメージ軽減を保証しており、これには重い鎧の方が優れて
います。

盾は通常、ACも回避力も増加させませんが、近接攻撃や、あなたを狙った一部の遠距離
攻撃をブロックすることができます。シールドスキルが不十分な状態で盾(特に大きな
シールド)を着用すると、白兵戦での効果が低下し、呪文を唱える能力が妨げられます。
また、十分なスキルを持っていない場合は回避力も低下し、当然盾を着用している間は
両手武器を扱うことができません。シールドは各ターンの最初の攻撃で最も効果的です
が、それ以降は攻撃が行われるたびに役に立たなくなります。バックラー、シールド、
ラージシールドの3種類があります。

一部の魔法の鎧には特別な力があります。これらのパワーは自動的に行われる場合があ
り、アーマーを着用するたびに影響を受けますが、場合によっては'a'コマンドでアク
ティブ化する必要があります。

'W'コマンドで鎧を着用し、'T'コマンドで鎧を脱ぐことができます。 '['を使用すると、
現在のギアを簡単に確認できます。

ほとんどの防具は、適切な巻物を読むことで改善できます。ボディアーマーとバードは、
それらが提供するACの基本値までエンチャントできます。シールドは、サイズに応じて
最大+3、+5、または+8までエンチャントできます。他のギアは+2までに制限されます。

食料と腐肉の割合
========================================

食事は非常に重要です。ダンジョンではさまざまな種類の食べ物を見つけることができ
ます。お腹が空いたときに食べなければ、やがて餓死してしまいます。戦ったり、重い
荷物を運んだり、呪文を唱えたり、魔法のアイテムを使用したりするとお腹が空きます。
飢えていると、戦闘の効率も低下します。 'e'コマンドで食べ物を食べることができま
す。

あなたは犠牲者の死体で食事をしたいと思うかもしれません（あなたがスプリガンで肉
を食べることができないか、あなたがミイラであり、食べる必要がなく、まったく食べ
ることができない場合は別です）。死体は食べ物と同じ'%'記号で表されますが、最初
に'c'コマンドで食べやすい部分を切り取らない限り、死体を食べることはできません。
空腹だと生の肉が窒息しやすくなります。最良の部分を切り取ると、いくつかのターン
がかかり、最終的には多数の'chunks'が生成されます。これらは上記のように'e'コマ
ンドで食べることができます。

コボルド、トロール、グールはいつでも喜んで生肉を食べます。

吸血鬼は特殊なケースです。この種族のメンバーは、新鮮な死体から血を飲むことを試
みることができます('e'コマンドを使用します)。経験レベル6に到達すると、死体から
血のポーションを瓶詰めすることもできます。これは、'a'bilitiesメニューを使用し
て行われます。

?魔法の巻物
========================================

巻物にはさまざまな魔法の呪文が刻まれており、良いものもあれば悪いものもあります。
最も便利な巻物の1つは識別の巻物です。これにより、インベントリ内のアイテムの機
能がわかります。ポーションやその他の巻物など、未確認のときに使用すると危険また
は無駄になるアイテムのためにこれらを保存しておくとよいでしょう。 'r'コマンドを
使用して巻物を読む(そしてそうすることで魔法を呼び出す)ことができます。

！魔法のポーション
========================================

巻物は装備や環境に影響を与える傾向がありますが、ほとんどのポーションは何らかの
形でキャラクターに影響を与えます。最も一般的なタイプは単純な治癒ポーションで、
ヒットポイントをいくらか回復し、多くの病気を治しますが、他にも多くの種類のポー
ションが見つかります。ポーションは'q'コマンドで飲む(酔わせる)ことができます。
有毒な薬を飲まないようにしてください。

/ワンド
========================================

幸運なことに、魔法のエネルギーが蓄えられたスティックを見つけることもあります。
ワンドにはそれぞれ一定量のチャージがあり、チャージがなくなるとワンドは機能しな
くなります。残りの使用回数を確認するには、杖を特定する必要があります。これは、
識別のスクロールで行うことができます。優れた召喚スキルを持つキャラクターは、杖
を召喚するだけでチャージ数を推測することもできます。残りのチャージ数を完全に確
認せずに杖を呼び出すと、一部のチャージが無駄になります。ワンドはミサイル武器と
同じように狙いを定めることができ、'V'で杖を呼び起こすことでそのパワーを解放す
ることができます。ターゲティングについてはセクションIを参照してください。自分
自身を狙うのに役立つ杖も多数あります。

＝指輪とお守り
========================================

魔法の指輪はダンジョンで見つかるアイテムの中で最も便利なものの1つですが、最も
危険なものでもあります。リングを装着するには'P'コマンドを使用し、リングを削除
するには'R'コマンドを使用します。両手に1つずつ、最大2つのリングを同時に着用で
きます。どちらの手に指輪をつけるかは、その機能にとって重要ではありません。両方
の薬指がふさがっている状態で指輪をはめようとすると、どちらを外すか聞かれます。
八足類は例外で、触手に最大8つの輪を付けることがあります。一部の呼び出し音は自
動的に機能しますが、他の呼び出し音はアクティブ化('a'コマンド)する必要がありま
す。

アミュレットは指輪に似ていますが、効果の範囲が異なります。お守りは首に掛けます
が、一度に一つだけ身に着けることができます。

'"'を押すと、身に着けているジュエリーをすぐに確認できます。

\|五線譜
========================================

魔法の杖にはいくつかの種類があります。一般的な呪文詠唱能力を強化するものもあれ
ば、特定のクラスの呪文のパワーを大幅に向上させるものもあります(他のものでは効
果が低下する可能性があります)。一部の杖は白兵戦でも使用できますが、杖のタイプ
に固有の召喚スキルとスキルを組み合わせて使用することで、特別な力を利用できない
限り効果は平凡です。破壊魔法流派を強化しない杖は戦闘力を全く持たない傾向があり
ます。

\|ロッド
========================================

ロッド('|')は、ロッドを振るっているときに'v'コマンドを使用して呼び出すことがで
きる固有の呪文を保持します。これらの呪文の有効性は、Evocationsスキルによって増
加します。彼らはロッドのエンチャント（再充電の巻物を使用して増やすことができま
す）とあなたのエヴォケーションスキルに従って再生する魔法のエネルギーのプールを
持っています。フルレングスの五線よりも短いため、棍棒として使用する場合は、五線
の代わりにメイス&フレイルスキルを使用します。

:本
========================================

ほとんどの本には、キャラクターが学習できる魔法の呪文が含まれています。 'r'コマ
ンドを使用して本を読むことができます。これにより、各呪文の説明にアクセスしたり、
'M'コマンドを使用してその中の呪文を記憶したりできます。

新しい呪文を手に入れることに加えて、キャラクターは古いものを処分したい場合もあ
ります。そうする最も便利な方法は、記憶喪失の巻物を読むことです。これにより、忘
れるべき巻物を選択できるようになります。ただし、そのような巻物が不足している場
合は、本の関連ページを切り取って、呪文を忘れることもできます。残念ながら、この
暴力的な手順により、必然的に本全体が消費されてしまいます。これを行うには、'r'
の本を読み、すでに学習した呪文を選択し、'F'を取得します。

一部の強力な魔法書では、内容を読むために一定量の魔法のスキルが必要です。

時々、スキルのマニュアルが見つかることがあります。これを携行すると、スキルのト
レーニングに使用すると、経験値が通常の2倍の効果が得られます。

{その他
========================================

これらは他のカテゴリーに当てはまらないアイテムです。ワンドと同じように、'V'で
呼び出すことができます。このカテゴリの特定のアイテムであるルーンには、エンドゲ
ームを開始する以外には何の機能もありません。ゾットの王国に入るには、少なくとも
3つ集める必要があります。特に生意気な冒険者の中には、腕力と悪知恵を使って10個、
さらには15個のルーンを回収したことを自慢する人もいますが、ゾットのテーマに関す
るほとんどの学者は、そもそもそのようなことはおそらく不可能であり、第2に、いか
なる点においても無意味な成果であることに同意しています。

$ゴールド
========================================

ショップを横断する場合、ゴールドはアイテムの購入に使用できます。金にはさらに難
解な用途もいくつかあります。

アーティファクト
========================================

武器、防具、宝石、魔法の本はアーティファクトになります。これらには、ランダムに
作成されたアーティファクト('randarts')と事前定義されたもの('unrandarts')の2つ
の形式があります。ランダーツには常に「黄金のバスタードソード」や「きらめく鱗の
メイル」などの珍しい名前が付いています。アーティファクトは、エンチャントを含め、
いかなる方法でも変更できません。

それとは別に、平凡なアイテムは1つの特別な特性を得ることができます。これらは'
ego items'と呼ばれ、例としては、ランニングのブーツ、炎の武器、目に見えないヘル
メットなどがあります。アーティファクトとは異なり、このようなアイテムはエンチャ
ントスクロールによって変更できることに注意してください。

すべてのエゴアイテムは特別な形容詞で示されますが、この方法で示されるすべてのア
イテムが特別なプロパティを持つ必要があるわけではありません(ただし、ポジティブ
またはネガティブなエンチャントが付いていることがよくあります)。

:全般:光る、ルーン文字。 :金属の鎧:光沢のある; :革の鎧:染色; :その他の防具:刺
繍。

****************************************
H. 呪文の詠唱
****************************************

魔法の呪文は、ダンジョンで生き残るための非常に重要な部分です。すべてのキャラク
ターは魔法の呪文を使用できます。

魔法に関連したスキルは多数ありますが、主要なものは呪文詠唱です。呪文詠唱は、使
用可能なMPの数を決定します。また、呪文を実際にキャストするときにいくつかの点で
役立ちます。次に、いくつかの一般的な魔法のエリア(召喚、ヘクス、チャーム、召喚、
ネクロマンシー、転移、変容)といくつかの要素エリア(火、氷、空気、地)、そして最
後に毒があります。特定の呪文は、最大3つのエリアに属することができます(したがっ
て、そのエリアのトレーニングが可能になります)。呪文の分野で優れていると、キャ
ストのチャンスが向上し、多くの場合、効果も向上します。

呪文は本に保管されており、ダンジョンで時々見つけることができます。 'r'を使用し
て本を読んで、そこに含まれる呪文を確認できます。そうすることで、個々の呪文の説
明を読むことができます。特定の呪文を記憶するには、'M'コマンドを使用します。

各呪文にはレベルがあります。呪文のレベルは、それを使用するために必要なスキルの
量を示し、それがどれほど強力であるかを示します。呪文のレベルは一定数しか記憶で
きません。数を確認するには、「'M'」と入力します。経験レベルを獲得するか、呪文
詠唱スキルを進めると、最大値が増加します。より強力な呪文を覚えるには、いくつか
のレベルを貯める必要があります。呪文を唱えると、一時的に魔法のエネルギーの一部
を消費して空腹になります(ただし、高い知力と呪文詠唱は呪文による空腹を防ぐのに
役立ちます)。 'II' (または'I!')を押すと、呪文の相対的な空腹コストが表示されま
す。飢餓コストは、この表示内の#マークの数の2乗にほぼ比例します。

'z' (Zapの場合)を押すと、記憶された呪文がアクティブになります。実際にキャスト
せずに、記憶されているすべての呪文のリストを表示するには、'I'を使用します。利
用可能な呪文には文字のラベルが付いています。このラベルは'='コマンドを使用して
自由に変更できます。呪文には、小文字と大文字の両方を割り当てることができます。
一部の呪文、たとえばほとんどのダメージを与えるものにはターゲットが必要です。タ
ーゲティング方法の詳細については、次のセクションを参照してください。

ほとんどの呪文には効果に上限があります。どんなに知的で熟練していても、マジック
ダーツで達成できるダメージには限界があります。一般に、'I'および'II'画面の出力
を見て、キャスト能力を把握することをお勧めします。これは、鎧や指輪を変更しよう
としている場合に特に便利です。

高レベルの呪文は唱えるのが難しく、時々ミスキャストする可能性があります(その結
果、魔法が無駄になり、場合によっては危険な副作用が発生する可能性があります)。
呪文を適切にキャストできない可能性は、スキル、知力、呪文のレベル、および重い鎧
を着ているかどうかによって異なります。呪文をミスキャストする可能性は呪文画面に
表示され、潜在的な重大度に基づいて色分けされます(黄色は中程度の可能性を表し、
赤は重大な可能性を表します)。

より強力な呪文の多くには欠点やリスクがあります。何かを唱える前に、呪文の説明(
呪文を見つけた呪文の本を読むことで得られます)を読む必要があります。

魔法を使う敵には注意！彼らの中には、あなたと同じくらい、あるいはそれ以上に魔法
を使うことができ、しばしばそれを賢く使います。

****************************************
I. 照準合わせ
****************************************

何かを投げたり、特定の杖を呼び出したり、呪文をキャストしたりすると、方向を尋ね
られます。どのモンスターをターゲットにするかをCrawlに伝える方法はいくつかあり
ます。

方向を尋ねられたら、'?'を押してください。ヘルプ画面が表示されます。それ以外の
場合は、次のコマンドを使用します。

- カーソルは、あなたの位置に最も近いモンスターをターゲットにします。以前に何か
  に向かって発砲していて、犯人がまだ視界に入っていた場合、カーソルは代わりに前
  のターゲットの上に止まります。
- '+'または'='を押すと、カーソルが次のモンスターに移動し、近い方から遠い方に移
  動します。'-'を押すと逆順に移動します。
- 方向キーを押すとカーソルが1マス移動します。場合によっては、人のいないマス目
  をターゲットにするのが便利な場合があります。
- ターゲットの選択に満足したら、Enter、Del、またはSpaceキーを1つ押してターゲッ
  トへ射撃します。'.'を押した場合、呪文や矢弾が外れてもターゲットのマスで止まり
  ます。これは、味方への誤射や、貴重な矢弾が深海に落ちるのを防ぐのに役立ちます。
- 気が変わった場合はEscapeを押してください。ターンは差し引かれません。

ターゲティング中にいくつかのショートカットがあります。

- キーパッドでShift-directionと入力すると、その方向にすぐに起動されます。
- 'p'または'f'を押すと、前のターゲットに向けて発砲します(ターゲットがまだ生き
  ていて視界に入っている場合)。このため、ほとんどのハンターは、'ff'を押してモ
  ンスターに弾薬を発射し、さらに'ff'ストロークで射撃を続けることで、長い距離を
  進むことができます。ただし、場合によっては、'+'または'-'コマンドを使用してタ
  ーゲットを切り替えると便利です。

自分自身をターゲットにすることも可能です。ヘイスティングやヒーリングなどの明ら
かに有利な効果は、実際にカーソルを自分に向け、あとは'.'、Enterなどを押すだけで
す。ただし、他の誰かをヒーリングまたはヘイストしたい場合は除きます。何か有害な
ものを発射しているときに自分自身をターゲットにした場合(これは賢明な場合もあり
ます)、確認を求められます。

最後に、':'キーを使用すると、呪文/ワンド/ミサイルのパスを非表示にすることがで
きます。

****************************************
J. 信仰
****************************************

あなたのキャラクターの崇拝を受け入れ、時には引き換えに恩恵を与える神、悪魔、そ
の他のさまざまな力が数多くあります。 '^'コマンドを使用して、崇拝する相手の要件
を確認できます。宗教が不便だと感じた場合は、いつでも信仰を放棄できます('a'コマ
ンドを使用します。ただし、ほとんどの神々は軽蔑されることを嫌います)。追加の詳
細が記載された2ページ目もあります。'^!'を押してアクセスしてください。

'p'コマンドを使用すると、神に祈ることができます。あなたの神が死体の犠牲を高く
評価するように求めている場合、死体の上で'p'を押すと、それらを神に捧げることが
できます。祈ることによって、神があなたのことをどう思っているかを知ることもでき
ます。神々によっては、祭壇で高い信仰値で祈ると贈り物を与える場合があります。そ
の場合は、'^'画面と'^!'画面で説明されています。

神があなたに適していると判断した力を使用するには、'a'コマンドを使用して能力メ
ニューにアクセスします。神から与えられた能力が呼び出しとしてリストされています。

職業によっては、最初から宗教的なキャラクターもいます。奴隷生活を捧げるために祭
壇で祈らなければならない人もいます。ダンジョンのいたるところに祭壇が点在してお
り、あなたのキャラクターは地表近くのどこかに特別な神殿があるという噂を聞いてい
ます。祭壇で'p'を押すと、その神の一般的な態度の説明を読むことができます。後で
本当にこのサークルに参加したいかどうか聞かれます。標準的な神のリストと、ダンジ
ョンに祭壇がすでに存在している神のリストを表示したい場合は、'Ctrl-O'を押してく
ださい。 '?/G'を押すと、標準的な神とあまり知られていない神について学ぶこともで
きます。

善良な神々は悪魔やアンデッドの信者を受け入れないことに注意してください。

宗教を持ってゲームを開始したい場合は、バーサーカー、カオスナイト、またはアビサ
ルナイトから職業を選択してください。

****************************************
K. 突然変異
****************************************

遺伝的に純粋な状態を維持できれば間違いなく素晴らしいことですが、ダンジョンには
有毒廃棄物と変異原性放射線が多すぎるため、それは不可能です。あなたのキャラクタ
ーが生理学的変化を起こすほどこれらの影響を受けている場合は、'A'コマンドでどの
程度異常になったかを確認し、'a'コマンドで制御可能な変異を発動できます。多くの
変異は実際にキャラクターにとって有益
ですが、厄介なものもたくさんあります。多くの変異には3つのレベルがあり、それぞ
れが1つの変異としてカウントされます。

また、特定の強力なエンチャント、特にヘイスト（凶暴化によって得られる種類ではあ
りません）や透明化など、システムが魔法のエネルギーを過剰に吸収するため、使いす
ぎると突然変異する可能性があります。ただし、影響を受けるには、急いでいるか透明
化されている間にかなりの時間を費やさなければなりません。ただし、強力なアイテム
の中には、危険なレベルの魔法のエネルギーを放射するものもあります。多くの場合、
魔法の放射線によって引き起こされる変異は有害な影響を及ぼします。

さらに、特定の死体には変異誘発性があり、変異の効果を持つトラップもあります。呪
文や変異を引き起こすポーションもいくつかあります。

不良の変異を取り除くことは、入手するよりもはるかに困難です。幸運な変異の試みに
より、実際に変異を削除できます。ただし、唯一の確実な方法は、治療薬変異を飲むこ
とです。これにより、1つ以上のランダムな変異を除去しようとします。

デモンスポーンは特殊なケースです。この種族のキャラクターは、レベルが上がると特
定の特別な変異を取得します。これらはシアンでリストされています。これらは永久的
なものであり、削除することはできません。 Demonspawnのパワーの1つが変異によって
強化されている場合、それは明るい色で表示されます。

多くの種族は、ケンタウロスやスプリガンのより速いスピード、またはトロールやコボ
ルドなどの食生活など、いくつかの特別な固有の特技から始まります。これらは、常に
ではありませんが、多くの場合、プリセット変異のようになります。このような固有の
機能が通常の変異によって増幅される場合、それは水色で表示されます。

一部の変異は一時的なものであり、より多くの敵を倒すと消滅します。これらは、変異
のリストに紫色でリストされ、一時的としてマークされています。

****************************************
L. ライセンス、連絡先および歴史
****************************************

ライセンス
  Crawlのライセンスについては、「licence.txt」を参照してください。ゲームのコン
  ポーネントのほとんどは、GNU General Public Licenseのバージョン2以降に基づい
  てライセンスされています。そうでないものは互換性のあるライセンスの下にありま
  す。

免責事項
  このソフトウェアは現状のまま提供され、明示的または黙示的な保証は一切ありませ
  ん。使用はユーザーの単独のリスクで行われます。ユーザーまたはユーザーの所有物
  に対する損害については、一切の責任を負いません。

Crawlについて議論したい場合は、公式フォーラムが最適です。

  https://crawl.develz.org/tavern

このゲームに関連するすべてのトピックは通常、勝利の物語('YAVP'、つまり
「また一つの勝利報告」)、特に最初の勝利(YAFVP)や亡くなったキャラクターの悲しい
話('YAAD'または'YASD'、つまり「また迷惑な/愚かな死」)を含め、温かい反応を示し
ます。

多くのプレーヤー、特にオンラインサーバー上のプレーヤーは、フリーノードIRCネッ
トワーク上の##Crawlにも頻繁にアクセスします。このIRCチャネルには、ゲームに関す
る役立つ情報や統計を提供する多くのボットも含まれています。

Stone Soupのホームページは次のとおりです。

  http://crawl.develz.org

最新バージョンのダウンロードへの直接リンクについては、このページを使用してくだ
さい。 https://crawl.develz.org/mantis でバグレポートを送信することもできます。
あなたのバグがリストにまだ含まれていないことを必ず確認してください。機能リクエ
ストは、代わりに公式フォーラムまたはCrawl.develz.orgの開発Wikiに投稿する必要が
あります。

Crawlの歴史はやや複雑です。Crawlは1995年にLinley Henzellによって作成されました。
Linleyは、CrawlをAngbandとNetHackに大まかに基づいていますが、これらのゲームの
いくつかの煩わしい側面を避け、彼自身のオリジナルのアイデアを多数追加しました。
Crawlはヒットし、リンリーは1999年3月にCrawlのバージョン3.30までを作成しました。
その後、開発者のグループによってさらなる作業が行われ、2000年2月に3.40がリリー
スされました。その中で、Brent Rossが単独のメンテナーとして登場し、2002年の4.0
ベータ26までのバージョンを作成しました。長い沈黙の作業の後、彼は大きな一歩を踏
み出しました。このアルファ版には多くの優れたアイデアが含まれていましたが、バラ
ンスの問題によりほとんどプレイできませんでした。その間、いくつかのパッチャーが
登場し、Crawlのインターフェースを大幅に改善しました。彼らのうちの何人かは新し
い開発チームを結成しました。 4.1.2のリバランスは非常に難しい作業であると考え、
Crawl 4.0ベータ26をフォークし、4.1.2やその他のソースから良いアイデアを選択的に
組み込むことにしました。このフォークはStone Soupであり、このマニュアルで説明さ
れているゲームです。 Stone Soupのリリースバージョンは、既存の多数のCrawlバージ
ョンとの混乱を避けるために0.1で再起動されました。

長年にわたり、Ax-Crawl、Tile Crawl、Dungeon Crawl Alternativeなど、他のCrawlの
亜種も存在していることに注意してください。

Crawl (ゾットのオーブ)のクエストのオブジェクトは、BASICで書かれたテキストアド
ベンチャーであるWizard's Castleから取られました。

****************************************
M. マクロおよびオプション設定
****************************************

Crawlは、キーマップによるキーの再定義をサポートします。これは、キーボードレイ
アウトによって一部のキーが使いにくい場合に便利です。マクロを定義することもでき
ます。マクロは、プレイをより便利にするコマンドシーケンスです。 'a'を他のキーに
マッピングすると、'a'のほぼすべての押下がその新しい方法(ドロップや振るなどを含
む)で処理されるため、お勧めできません。 'a'を他のキーにマクロすると、コマンド
キー 'a'のみが変更されます。

ゲーム内で'~'キーを使用してキーマップとマクロを設定できます('Ctrl-D'も機能しま
す)。これにより、現在のすべてのキーバインドとマクロを保存することもできます。
または、macro.txtファイルを直接編集することもできます。両方の詳細と例について
は、「macros_guide.txt」を参照してください。

Crawlは、インターフェイスの柔軟性を高める多数のオプションをサポートしています。
これらについては、options_guide.txtファイルに完全に文書化されています。オプシ
ョン自体は、ファイル~/.crawlrc (UNIXシステムの場合- init.txtを~/.crawlrcにコピ
ー)またはinit.txt (Windowsの場合)に設定されます。

いくつかのインターフェイスルーチンは外部Luaスクリプトにアウトソーシングされま
す。標準ディストリビューションでは、これらはdat/clua/ディレクトリにあります。
簡単な説明については、単一のスクリプトを参照してください。

一般に、Crawlはすべてのマシンで迅速に実行されます(Linux、Windows、および程度は
低いですが、OS Xやその他のUniceではすぐにコンパイルできます)。何らかの理由で、
マシン上でCrawlの実行が許容できないほど遅いことが判明した場合は、状況を改善す
る可能性のあるいくつかの対策があります。

  - 移動中の画面の再描画を回避するには、travel_delay = -1を設定します(これは、
    リモートサーバーでプレイする場合に特に便利です)
  - タイルではなくコンソールモードでプレイしてみてください

****************************************
N. ゲームの方向性
****************************************

一言で言えば、このゲームは戦術的なファンタジーをテーマにしたDungeon Crawlを目
指しています。戦略性も重視し、絶妙なゲームプレイとインターフェースを追求してい
ます。ただし、ストーリーやクエストを期待しないでください。

Crawlの特定の設計上の決定について熟考するかもしれません。このセクションでは、
それらのいくつかを説明していきます。他のローグライクゲームに慣れていて、違いに
ついて少し職業したい場合にも興味深いかもしれません。 Crawl開発の主な柱は次のと
おりで、そのほとんどについては以下で詳しく説明します。これらの多くは、Linleyの
最初のバージョンに遡ることに注意してください。

主な設計目標
  * プレイヤーの腕前が明確な差を生む、挑戦的でランダムなゲームプレイ
  * 意味のある選択（考えるまでもない選択をなくす）
  * 単純作業の反復を避ける（稼ぎ行為を不要にする）
  * 手間のかからないインターフェイスと初心者支援を実現するゲームプレイ

副次的な設計目標
  * 明瞭さ（ネタバレを必要としない遊びやすさ）
  * 内部的な一貫性
  * リプレイ性（分岐、種族、プレイスタイル、神々の活用）
  * 場違いに強いモンスターの適切な活用

バランス
========================================

バランス、または不均衡であるという概念は非常に曖昧です。これが私たちの定義です
: Crawlは挑戦的なゲームになるように設計されており、そのランダム性でも有名です。
ただし、これは勝利が任意の運の問題であることを意味するものではありません。プレ
イヤーのスキルが最も大きな影響を及ぼします。ですから、確かに、あなたが破滅する
運命にある状況もあるかもしれません。いかなる行動もあなたの命を救えなかったかも
しれません。しかし、ゲーム中盤以降、ほとんどの死はこのタイプではなくなります。
この段階までに、ほとんどすべての死傷者は実際のミスに遡ることができます。戦術的
なものではない場合は、間違ったスキル(広すぎるまたは狭すぎる)、リソースの賢明で
ない使用(保守的すぎるまたはリベラルすぎる)、部門/神/ギアに関する誤った決定など、
戦略的なタイプのものです。

避けられない死の可能性は、コンピュータゲームではより大きなテーマです。理想的に
は、このようなゲームは非常に挑戦的で、ランダムなレイアウトとランダムなアクショ
ンコースの両方を持ちながらも、完璧なプレイで勝てることができます。この目標は達
成できそうにありません。したがって、最適なプレイが勝利を確実にするという意味で
は、コンピューターゲームはソフトになる可能性があります。ただし、パズルとは別に、
これはゲームが最初から解決されていることを意味します。ここで、人間のゲームマス
ターの欠如が明らかです。あるいは、避けられない死が発生する可能性があるという意
味で、それらは困難である可能性があります。私たちは、後者の選択の方が長期的には
はるかに楽しいものになると感じています。

Crawlには、ランダム性を調整するための膨大な数の手作りの金庫/マップがあります。
このようなボールトの配置、および多くの場合コンテンツの一部もランダムですが、い
くつかの利点があります。ボールトには、単にランダムなモンスターとレイアウト生成
だけでは取得するのが非常に難しい課題があります。いくつかのテーマを中心にして、
さらなる没入感を提供する場合があります。最後に、それらには戦利品が含まれている
ことも多く、プレイヤーは安全か貪欲かの決断を迫られます。

(次のトピックは、バランスの下に提出することもできます。バランスが私たちにとっ
て意味しないものについては、リプレイ可能性を参照してください。)

無理のない者たちに対する聖戦
========================================

Crawlで非常に重要な点は、簡単なことを避けることです。ゲーム全般について言えば、
当然のことである限り、開発チームは実際にはまったく面白くない「選択肢」を提供す
ることに多大な労力を費やしたことを意味します。そしてそれは楽しむための恐ろしい
機会の損失です。この例としては耐性があります。永続的なソースはほとんどなく、ほ
とんどが選択を伴うもの(指輪や特定の鎧など)、または半永久的なもの(変異など)です。
もう1つの例は、ほとんどのアーティファクトがランダムに生成されるという事実に起
因する、明確な最高のアイテムが存在しないことです。さらに、獲得スクロールは一般
にランダムなアイテムを生成するため、非ランダムなアーティファクトさえも望むこと
はできません。同様に、命を救う確実な手段もありません（最も近い手段は、まばたき
を制御することや、一部の神々の宗教的地位が高いことです）。

耐研削性
========================================

もう1つの基本的な設計原則は、研削(スカムとも呼ばれます)を回避することです。こ
れらは、リスクが低く、多くの時間がかかり、ある程度の報酬をもたらす活動です。こ
れはプレイヤーに退屈を促すため、ゲームのデザインにとって良くありません。さらに
悪いことに、そうすることが最適な場合もあります。私たちはこれを回避しようとして
います。

これでお店が買わない理由が説明されます。そうでないと、プレイヤーは売るアイテム
を求めてダンジョンを歩き回ることになります。別の例:利用可能な無限の商品はあり
ません。食品、モンスター、およびアイテムの生成は、通常、無限のプレイをサポート
するには十分ではありません。照明をいじらないこともこのカテゴリに当てはまります。
プレイヤーがキャンドル/トーチを持ち歩かなければならない場合、気分に利点がある
かもしれませんが、ゲームプレイ上の利点はまだ見当たりません。 Crawlが目指す奥深
い戦術的なゲームプレイには、永続的なダンジョンレベルが必要です。多くの場合、キ
ャラクターは降下するか戦闘するかの選択を迫られます。他の多くのローグライクと同
様に、Crawlでは注意が美徳ですが、キャラクターを奥深くまで駆り立てる強い力があ
ります。

インタフェース
========================================

インターフェイスは、ゲームプレイを簡単にするために徹底的に設計されています。こ
れは些細なことのように聞こえますが、私たちは本気でそう思っています。面倒だが必
要な雑務はすべて自動化する必要があります。例としては、長距離の自動移動、探索、
メモ作成などが挙げられます。また、さまざまな設定にも対応できるように努めています。
ASCIIとタイルの両方がサポートされています。 viキーやテンキーも同様です。ドキュ
メントは豊富で、コンテキストに特化しており、ゲーム内でいつでも利用できます。最
後に、チュートリアルを通じて簡単に開始できるようにします。

明瞭さ
========================================

物事は直感的に機能する必要があります。 Crawlはネタバレなしで確実に勝てます。重
要だが隠された詳細(つまり、ネタバレの対象となる事実)に関して、私たちのポリシー
は次のとおりです。ネタバレになるものを一度発見する喜びは素晴らしいものです。
（そして、ネタバレを読む必要があると感じた場合は、開始する前に消えます。これは
正当な感情です。）一方で、透明なルールから生じる、常に変化し、予期せぬ、挑戦的
な戦略的および戦術的な状況に対処する喜びは、何度でも楽しめます。とはいえ、多く
の場合、定性的なフィードバックの方が正確な数値よりも優れていると私たちは考えて
います。

具体的には、ゲームプレイメカニクスを明示的に(マニュアルまたはゲーム内フィード
バックによって)排除するか、単純なアプローチで十分だと思われる場合はミニマック
ス担当者に任せます。

一貫性
========================================

語るべきプロットはありませんが、ゲームは一貫したCrawlユニバースを舞台とする必
要があります。たとえば、アーティファクトの名前は雰囲気に合っている必要があり、
金庫は賢明に配置されている必要があり、モンスターも同様に何らかの形で適合してい
る必要があります。本質的に、これはプレイヤーの没入感に関するものです。そのため、
念頭に置いておくのは良いことですが、一貫性はゲームプレイにとって常に二の次です。
典型的な例は、プレイヤーとモンスターの動作です。これらを同一(または類似)にしよ
うとしていますが、場合によっては区別しておかなければならない十分な理由がありま
す。

リプレイ性
========================================

これは実際には非常に重要ですが、ある意味では主要な設計目標の必然的な結果にすぎ
ません。これらに加えて、Crawlを何度も楽しくプレイするのに役立ついくつかのポイ
ントがあります。

多様性
  プレイヤーに選択肢があるときは常に、種族、神、武器、または呪文の選択であって
  も、さまざまなオプションは真に異なるものである必要があります。異なる名前(場
  合によっては番号も)の武器を何十も提供しても、最終的にはすべて同じように機能
  するのであれば、役に立ちません。

さまざまな種族
  これはスキルと適性システムによるものです。同様に重要なのは、種族に組み込まれ
  た開始ボーナス/ハンディキャップです。これらはプレーに大きな影響を与えること
  がよくあります。私たちにとってバランスとは、職業と種族のすべての組み合わせが
  同等にうまく動作することを意味するものではありません。他のものよりもはるかに
  困難なものもありますが、これは問題ありません。ただし、各種族には少なくともい
  くつかの職業がかなりうまく機能します。

ダンジョンのレイアウト
  ベテランプレイヤーでも、墓や地獄はエキサイティングだと感じるでしょう(生命の
  危険にさらされる状況が常に発生するように設計されています)。これらおよびその
  他のブランチは、特定のキャラクターのビルドアップに適合する場合と適合しない場
  合があります。ちなみに、ゲームは無敵状態に到達できれば意味がないと強く思って
  います。

宗教
  これは、寺院に到着して神を選択することがほとんどのゲームの最初の主要なタスク
  になるため、新規プレイヤーに対応します。しかし、神の選択は種族と同じくらい重
  要になる可能性があるため、宗教は経験豊富なプレイヤーにとってリプレイ性を高め
  るポイントでもあります。

プレイスタイル
  種族、職業に関連していますが、これらを包括するものは、近接指向のファイター、
  スタバーなど、根本的に異なるプレイスタイルです。スタイルを移行するかどうか(
  そしていつ!)を決定することで、ゲームの成否が決まります。

深みから出て
========================================

時折、Crawlの不公平なOOD (徹底的な)モンスターに関する議論が、ダンジョンの2番目
のレベルのドラゴンのように現れます。これらはバグではありません。実際、これらは
ランダム性の設計目標の一部です。この場合、それらは追加の動機としても機能します。
多くの状況で、OODモンスターは何とか生き残ることができ、キャラクターとの精神的
な絆は確実に高まります。 OODモンスターは、浅いレベル、またはクリアされたレベル
でもまだ簡単ではないようにすることで、プレイヤーを警戒し続けるのに役立ちます。
同様に、序盤にアビスへ送られても、それだけで敗北ではありません。脱出方法は複数
あり、そこから生還できれば誰にとっても心躍る経験になります。

########################################
付表
########################################

****************************************
1. 種族一覧
****************************************

.. note::
   'A'を使用して、種族にどのような特殊性があるかを確認します。また、一部の種族
   には、'a'能力メニューからアクセスできる特殊な能力があります。追加の攻撃を可
   能にする物理的特性を持つものもいます。

人間
  人間は働き者で向上心があり、新しいことをすぐに学ぶ傾向があります。人間は、プレ
  イヤーが利用できるすべての種族の中で最も多用途です。人間はレベルが速く進み、
  ほとんどのスキルで同等の能力を持っています。

丘オーク
  丘オークは、地下に住む同族(洞窟オーク)の富をうらやみ、略奪と冒険を求めて地上
  から降りてきたオークです。

  丘オークはミノタウロスと同じくらい頑丈ですが、人間と同様の魔法のエネルギー
  を蓄えています。彼らの得意分野は総当りの戦いであり、ほとんどの手持ち武器(特
  に彼らが得意とする斧)の使用に熟練していますが、ミサイル兵器の使用は特に得意
  ではありません。丘オークはほとんどの種類の魔法を無難に使いこなし、特に火の
  扱いに優れています。

  多くのオークは他のすべての種族や存在よりも優れていると感じており、その考えを
  中心に宗教を形成しています。オークのみがオークの神であるベオを崇拝できます。
  彼らはオークの司祭が視界に入れば、いつでもベオに改宗できます。

マーフォーク
  マーフォークは、半分人間、半分魚のハイブリッド種族で、通常は海や川に住んでお
  り、陸地に向かうことはめったにありません。ただし、マーフォークはいくつかの神
  話が示唆するほど陸上に制限されていません。尻尾は水から出るとすぐに足に変わり
  ます（同様に、水に入るとすぐに足が尻尾に変わります）。彼らの敏捷性はしばしば
  誤って判断されますが、水中でも陸上でも驚くほど機敏である傾向があります。水泳
  の達人である彼らは、溺れることを恐れる必要がなく、水の中を非常に素早く移動し
  ます。

  マーフォークは、水中で戦うための最も効率的な方法である突きと組み技を中心に武
  術を強化してきました。したがって、彼らは他の武器よりも竿武器と短い剣を好みま
  すが、長い剣も非常にうまく使用できます。

  スペルキャスターとして、彼らは特定の分野で非常に優れている傾向があります。彼
  らと水との神秘的な関係により、彼らは毒や氷の魔法を使いやすくなり、材料成分と
  して水を使用することもあります。マーフォークの伝説的な水の魔法は古代に失われ
  ていますが、その親近性の一部はまだ残っています。彼ら自身の形態形成マトリック
  スの不安定性により、彼らは非常に熟練した変換者となったが、他のほとんどの魔法
  は彼らにとって異質なものであるようだ。

ハーフリング
  ハーフリングは人間の約半分の大きさであることから名付けられ、小さな村に住んで
  います。彼らはシンプルな生活を送り、シンプルな興味を持っています。時々、特に
  落ち着きのないハーフリングが冒険を求めて村を離れることがあります。

  ハーフリングは非常に小さいですが、その大きさに比べて驚くほど丈夫で、突然変異
  誘発効果に対する生来の耐性さえ持っています。彼らは短い刃と盾をうまく使いこな
  すことができ、長い刃でも扱いやすく、スリングを使った遠距離戦闘に優れています。
  彼らはまた、非常にステルスで器用ですが、魔法は苦手です（魅了、転移、空中魔法
  を除く）。彼らは人間と同じくらい急速にレベルを上げていきます。ハーフリングは
  大きな武器を扱うことができません。

コボルト
  コボルドは小さくて醜い生き物で、ほとんど救いのない特徴を持っています。あなた
  自身がたまたまコボルトでない限り、彼らは一緒に多くの時間を過ごしたい種類の人
  々ではありません。

  彼らはハーフリングよりも強く、敏捷性に劣る傾向がありますが、ほとんどの種類の
  魔法、特に死霊術を使用する才能がわずかに優れています。彼らは戦闘において、特
  にショートブレード、メイス、クロスボウの使用に優れており、魔法の道具の使用に
  も非常に熟練しています。彼らは多くの場合、腐肉（お腹が空いていなくても食べる
  ことができます）を食べて生き延びる腐肉食動物として生きていますが、肉食性で肉
  しか食べることができません。コボルドは人間と同じくらい早くレベルが上がります。
  ハーフリングと同様に、コボルドは大きな武器を扱うことができません。

スプリガン
  スプリガンはエルフに遠い関係にある小さな魔法の生き物です。彼らははしゃいだり、
  いたずらっぽい呪文を投げたりするのが大好きです。

  彼らは戦闘能力が低く、物理的な回復力もほとんどありませんが、攻撃を回避するこ
  とに非常に熟練しています。彼らは、召喚、召喚、死霊術、そしてエレメンタル呪文
  などの破壊的な魔法が苦手です。その一方で、他の魔法にも優れており、静かに素早
  く移動するのが得意です。彼らのスピードは非常に優れているため、スプリガンはケ
  ンタウロスを追い越すことができます。体が小さいため、必要な餌はほとんどありま
  せん。ただし、草食動物なので肉は食べられません。また、その大きさにより、ほと
  んどの鎧を着用することができません。彼らは大きな武器を扱うことができず、ほと
  んどの小さな武器でもスプリガンは両手で扱う必要があります。

ナーガ
  ナーガはハイブリッド種族です。腰から上は人間で、足の代わりに大きな蛇の尾が付
  いています。

  彼らはほとんどのことにかなり優れており、マーフォークと同じ速度で経験レベルが
  上がります。彼らはもともと毒に耐性があり、目に見えない生き物を見ることができ、
  丈夫な皮膚を持っていますが、尻尾は比較的遅く、他の生き物の足ほど速く動かすこ
  とができません（これは移動速度にのみ影響します。他のすべての行動は通常の速度
  です）。彼らの体型は、ほとんどの鎧から完全な保護を得ることができません。ナー
  ガの最大の強みはステルスです。ナーガは気づかれずに移動するのが非常に得意です。
  彼らの尻尾は最終的には戦闘中に敵を締めつけるほど強く成長します。

  ナーガは毒を吐くことができます。この毒の範囲、精度、ダメージはナーガの経験レ
  ベルとともに増加します。

ケンタウロス
  ケンタウロスは、別の種族ハイブリッド生物、つまり人間の胴体を持った馬です。普
  段は森に住んでおり、狩猟で生きています。

  ケンタウロスは4本足で非常に素早く移動でき、弓やその他のミサイル兵器の扱いに
  優れています。彼らはまた、特定の武器スキルの習得が遅い一方で、一般的に戦闘に
  関しては合理的です。彼らは経験レベルの進歩が非常に遅く、魔法の使用に関しては
  むしろ平均以下です。体が大きいため、生きていくためにはもう少し余分な餌が必要
  です。ナーガと同様に、彼らは身に着けている鎧からの保護が劣っています。

オーガ
  オーガは巨大で分厚い生き物で、通常は賢いというよりも強く、まったく機敏ではあ
  りません。彼らは体が大きいため、小柄な人々よりも飢えが大きくなります。オーガ
  は人間とほぼ同じくらい早く成長します。

  殴打を避けるために彼らが好む方法は、回避と盾の使用です。多くのオーガは、大型
  の鈍器を扱うのが自然だと考えています。 （無数の致命的な事件により、彼らはほ
  とんどの刃物はそのままにしておくべきだと学んだ。）高度な形式のミサイル戦闘は
  どれも彼らにとってあまりにもぎこちないものであるが、彼らは物、特に岩を投げる
  のが得意である。

  予想に反して、オーガは無知な野獣にはなりません。彼らは魔法の未熟な才能を持っ
  ており、驚くべきスピードで呪文詠唱の基本を習得することができます。しかし、よ
  り難解な魔法の流派は彼らにとって馴染みがなく、習得率も低いです。

トロール
  トロルはオーガに似ていますが、さらに厄介です。彼らは、腐った緑色から泥だらけ
  の茶色まで、あらゆる色の厚くてこぶのある皮膚を持ち、厚い毛皮の斑点で覆われて
  おり、口にはイコールが滴る牙でいっぱいです。

  彼らは爪で生き物を引き裂き、最もひどい傷からも非常に早く再生することができま
  す。彼らは実にゆっくりと、ハイエルフと同じくらいゆっくりと学習し、生き残るた
  めに大量の食物を必要とします。

ミノタウロス
  ミノタウロスは、人間の体と牛の頭を持つハイブリッドのさらに別の種族です。彼ら
  は曲がりくねった通路が本能的に好きなため、ダンジョンを探索します。

  ミノタウロスはあらゆる形態の物理戦闘に非常に優れていますが、あらゆる種類の魔
  法を使用するのは非常に苦手です。彼らは一部の頭装備を除いてすべての鎧を着るこ
  とができます。接近戦になると、ミノタウロスは攻撃しようとする者に反射的に頭突
  きをする傾向があります。

天狗
  天狗は、伝説的な暴力性癖を持つ古代の恐れられている鳥人間です。基本的に鳥のよ
  うな頭と爪のある足を持つ人型の天狗は、兜とブーツを除くあらゆる種類の鎧を着る
  ことができます。翼がないにもかかわらず、強力な天狗は魔法のように飛ぶことがで
  き、この種族の非常に強力なメンバーは無限に空中に留まることができます。飛行中
  は移動速度と回避力がわずかに増加します。

  彼らは、魔法の戦闘術（召喚、召喚、そして程度は低いが死霊術）を含む、あらゆる
  形式の戦闘の専門家です。空気と火の属性魔法が得意ですが、氷と土の魔法は苦手で
  す。天狗はいかなる隷属も好まないため、呪術を使うのが苦手です。彼らの軽い鳥の
  体は、大きな怪我には耐えられません。

半神
  半神は、どんなに遠く離れていても、神または天使の祖先を持つ定命の者です。それ
  らは、魔法の実験や古くから行われている次元間異種生成など、さまざまなプロセス
  によって作成できます。

  半神は多かれ少なかれ定命の部分の種族のメンバーに似ていますが、優れた属性(Str、
  Int、Dex)を持ち、非常に堅牢です。彼らはまた、大量の魔法のエネルギーを利用す
  ることもできます。欠点としては、彼らは他のどの種族よりも経験の進歩が遅く、ス
  キルを獲得するのが人間よりもわずかに遅く、そのステータスにより、他のクラスの
  存在が利用できるさまざまな神や力を崇拝することができません。

デモンスポーン
  デモンスポーンは、半死の者、半地獄の恐ろしい生き物であり、半神の裏返しです。
  デモンスポーンは、魔法の実験、繁殖、不浄な協定など、さまざまな方法で作成でき
  ます。多くのデモンスポーンは最初は純粋な定命の個体と区別がつかないかもしれま
  せんが、必然的に角、鱗、その他の異常な特徴が成長します。このクラスの存在の強
  力なメンバーは、変異としてリストされているさまざまな不浄な能力も開発します。

  デモンスポーンは経験がゆっくりと進み、ほとんどのスキルを半神とほぼ同じ速度で
  学習します。ただし、彼らは戦闘と召喚術では少し優れており、死霊術と召喚術では
  はるかに優れています。半神とは異なり、彼らは神を引き受けることができますが、
  すべての人が神を受け入れるわけではないことに注意してください。

ディープ・ドワーフ
  ディープ・ドワーフは背が低くて丈夫な人々で、絶滅した地上の親戚とは異なり、地
  下の故郷を離れたことはありません。何世代にもわたってそこに住んでいたため、彼
  らは青ざめ、自力で再生する能力をすべて失い（また、単に再生を早める効果を受け
  入れることもできません）、時間の経過とともに主な特性の喪失から回復する能力も
  すべて失いました。一方、ディープドワーフは、少量のダメージに即座に対抗する能
  力を開発しました。彼らは地球への共感によって周囲の状況を感じます。この能力は
  経験レベルが上がるにつれて威力が増します。

  生まれつきの治癒力が欠如しているため、冒険や戦闘に出かけるディープドワーフは
  ほとんどいません。杖を持ってくる人は傷を治すか、神の助けに頼ることになります。

  当然のことながら、ディープドワーフは打撃やダメージを回避するあらゆる技術に熟
  達しています。攻撃面では、彼らは斧、クロスボウ、スリングの熟練した使い手です。
  ディープ・ドワーフは高度に霊的な存在であり、部外者によって実際の霊として描か
  れることがよくあります。このため、呼び出しを含むスキルは優れています。彼らは
  土と死の魔法に最も慣れており、最終的にはネクロマンシーの暗い力に対してある程
  度の耐性を獲得します。

  ディープドワーフは杖をいじって再充電することができます。ただし、そうするたび
  に、魔法の本質が少しずつ失われます。

ネコ科動物
  ネコ科動物は、知覚力を与えられた猫の品種です。もともと彼らは、主人の儀式を助
  けるために魔法で強化された魔女の使い魔でしたが、多くは放棄したり、長生きした
  り、少なくとも1つのケースでは、元の主人を骨抜きにして外界に出ました。

  フェリッドはスピーチやほとんどの魔法を完全に使用することができますが、鎧や武
  器を使用できないため、非常に不利な状況にあります。すべてのネコ科動物と同様に、
  ネコ科動物は植物性食品では成長できず、生き残るためには肉が必要です。

  彼らの敏捷性とステルス性は伝説的であり、到達困難な場所に到達する能力も同様で
  す。彼らはほとんどの種族よりも速く動きますが、ケンタウロスやスプリガンほど速
  くは走りません。ネコ科動物は非常にゆっくりとレベルを上げます。彼らはさまざま
  な形の魔法に熟練していますが、生の元素魔法についてはそれほど熟練していません。

  ネコ科動物はレベルが上がると追加のライフを獲得します。死亡すると、安全な場所
  に復活しますが、その過程で経験レベルを失います。

八足動物
  マダコの陸上能力を持つこれらの近縁種は、人間と同じくらいの速さで移動すること
  ができ、さらに水中を泳ぐ能力を保持していますが、その二重適応は形状を変えるマ
  ーフォークほど優れていません。

  八足動物には触手の形をした足が8本あり、移動するにはそのうち4本が必要です。触
  手には指がありませんが、アイテム操作に関しては2本の触手は人間の腕にほぼ相当
  します(4本の両手武器を扱う場合も含む)。彼らはゆるい帽子以外の鎧を使用できま
  せんが、盾をうまく扱うことができます。彼らが持つもう一つの特徴は、各触手に1
  つずつ、計8つの指輪を着用できることです。

  彼らは生来の迷彩能力によりステルス能力に優れており、毒についての知識も豊富で
  す。彼らはまた、触手を使って敵を締め付けることもできます-場合によっては一度
  に複数の敵を締め付けることもできます。

ガーゴイル
  普通の石のガーゴイルと生き物を掛け合わせたようなガーゴイルは、岩に親近感を持
  つ恐ろしいヒューマノイドです。彼らは低い健康状態を持っていますが、レベルが上
  がるにつれてさらに増加する大量の生来の鎧を持っています。最終的に彼らは継続的
  に飛行する能力を獲得します。

  ガーゴイルは部分的に生きているため、毒に対する耐性、電気に対する耐性、および
  死霊術の影響からの保護を与えられます。彼らは生来の鎧によって強力な近接戦闘機
  を備えており、鈍器や素手格闘の扱いにも当然熟練しています。彼らはまた、優れた
  地球ベースの魔術師になることもできます。

ギ酸類
  フォーミシッドは、人型アリの種族です。小さな昆虫の祖先と同じように、フォルミ
  シッドは物理的側面と魔法的側面の両方で土の仕事に熟達しています。彼らの能力は、
  その多くが数万年前のものである巨大な地下社会や構造物を掘るために使用されてき
  ました。

  おそらく残念なことに、彼らは地球との強い結びつきにより、テレポートや急送の影
  響をまったく受けません。ギ酸は完全な停滞感をもって地球に結びついています。こ
  れはダンジョン冒険者にとって一見悪い特性のように見えますが、スタシスにはさま
  ざまな種類の厄介な呪文や呪いを防ぐという有益な効果があります。

  自重の10倍を持ち上げる能力を持つフォーミシッドは、オーガに匹敵する腕力を持っ
  ています。これと、腕が4本あるという事実により、Formicidの戦士は盾と両手武器
  の両方を同時に装備することができます。

  フォーミシッドは優れた土と毒の魔術師を作りますが、近接戦闘と遠距離戦闘の両方
  でも非常に有能です。彼らはもともと空気魔法や魔法が苦手です。

ヴァイン・ストーカー
  しなやかな形状のヴァインストーカーは、太い蔓の塊を擬人化したものです。彼らは
  かつて人間の形をしたコアを持っており、死の直前に魔法の蔓によって寄生されます。
  他に目立った特徴はなく、その顔は不釣り合いで凶悪な口で支配されており、それに
  よって敵の魔法のエネルギーを混乱させ、貪り食います。

  魔法は彼らの体を自由に通り抜け、彼らが受けるダメージは健康と魔法の蓄えに分割
  されます。また、驚くべき速度で物理的に再生します。しかし、これらの特性には代
  償が伴います。彼らの体の二重の性質により、彼らは極度に虚弱になり、傷を治すた
  めの薬や杖の恩恵を受けることができません。

  適応の生きた例であるVine Stalkersはすぐにレベルアップし、全面的な攻撃スタイ
  ルに適しています。彼らのステルス能力を信頼して獲物を選び、戦いで負った傷を回
  復する能力を信じています。しかし、種族の多くのメンバーは非常に有能に魔法を操
  り、蓄えが少なくなり始めるとハイブリッドスタイルに切り替え、貪欲に噛むたびに
  魔法の覆いと呪文の燃料を補充しているのが見られます。

エルフ
========================================

エルフにはさまざまな種族があります。エルフは皆、体は小さいですが長命で、人間よ
りも機転が利きますが、新しいことを学ぶのが遅い場合があります。エルフは、ステル
ス、剣術、弓術など、ある程度の技巧を必要とするスキルを使用することに特に優れて
いますが、強引な戦闘や洗練されていない形式の戦闘は苦手とする傾向があります。彼
らは重い鎧を不快に感じます。

フェイの性質により、すべてのエルフは魔法全般、特に元素魔法の使用に優れています
が、他のタイプの魔法に対する親和性は、さまざまなサブ種族によって異なります。

ハイエルフ
  これは背が高く強力なエルフ種族で、ゆっくりとレベルが上がり、必要な経験値は人
  間の半分です。知力と器用さは良好ですが、腕力では苦戦します。人間に比べてHPが
  少ない代わりに魔力が多い。全種族の中で刃と弓の扱いが最も得意です。彼らは死霊
  術や土魔法、毒魔法はあまり得意ではありませんが、他のほとんどの魔法、特に空気
  や魔法には非常に熟練しています。

ディープエルフ
  これはエルフの種族で、はるか昔に外界から逃れ、地下の暗闇に住んでいます。そこ
  で彼らは精神力を発達させ、あらゆる形態の魔法（死霊術や土魔法を含む）に対する
  天性の才能を進化させ、新しい環境に肉体的に適応し、ハイエルフよりも背が低く弱
  くなり、すべての色を失いました。近接戦闘は苦手ですが、遠距離からの戦闘には優
  れています。彼らはハイエルフと同じ速度でレベルを上げます。

アンデッド
========================================

墓の向こうから持ち帰られた生き物として、アンデッドは本来、毒、負のエネルギー、
苦痛の影響を受けません。寒さの影響を受ける暖かさがほとんど残っていない。変異の
影響を受けません。

プレイヤーが利用できるアンデッドには、ミイラ、グール、ヴァンパイアの3種類があ
ります。

ミイラ
  これらは、復讐や償還を求めて、あるいは単にそうしたいから深海へと旅するアンデ
  ッドの生き物です。

  ミイラはレベルの進行が遅く、戦闘、呪文詠唱、死霊術を除くすべてのスキルで人間
  の半分の速度で進みます。レベルが上がるにつれて、彼らはますます死の力に触れる
  ようになりますが、生き物にのみ影響を与えるいくつかの種類の死霊術は使用できま
  せん。死霊術の魔法の副作用はミイラにとって比較的無害な傾向があります。しかし、
  乾燥した体は非常に燃えやすいのです。また、彼らは食べたり飲んだりする必要がな
  く、いずれにしても食べることも飲むこともできません。

グール
  グールは、ゆっくりと朽ちていく恐ろしいアンデッドの生き物です。グールは何年も
  墓の中で眠ることができますが、生きている人々の間を歩くために立ち上がったとき、
  彼らは生き残るために肉を食べなければなりません。生の肉が好まれており、グール
  はそれを消費することで治癒し、永遠の腐敗の影響を逆転させます。

  彼らはほとんどのことを行うのがあまり得意ではありませんが、爪を使えばまともな
  非武装の戦闘機を作り、墓との接触により、それほど困難なく氷、土、死の魔法を使
  用できます。

吸血鬼
  吸血鬼もアンデッドの一種ですが、新鮮な血を摂取することで生き返るという特徴が
  あります。無血吸血鬼はアンデッドのすべての特性を備えていますが、失われた物理
  的属性を取り戻したり、時間の経過とともに傷から再生したりすることはできません。
  特に、再生速度を高める魔法のアイテムや呪文は機能しません（ただし、神聖なもの
  は機能します）。一方、血で満たされた吸血鬼は非常に早く再生しますが、すべての
  アンデッドの力を失います。吸血鬼は決して飢えることはありません。彼らは'e'コ
  マンドを使用して新鮮な死体から飲むことができます。成長すると、彼らは素早いコ
  ウモリに変身することを学び、その後、新鮮な死体から血のポーションを引き出す方
  法を学びます。

ドラコニアン
========================================

ドラコニアンは人間とドラゴンのハイブリッドです。形状は人型で、ほぼ人間の大きさ
で、翼、尾、鱗状の皮膚を持っています。ドラコニアンは、最初は茶色の鱗を持つ未熟
な形態ですが、力が成長するにつれて、さまざまな色になります。これはキャリアの初
期段階で起こり、色は行動ではなく染色体によって決まります。

ほとんどのタイプのドラコニアンはブレス武器や特別な耐性を持っています。ドラコニ
アンはボディーアーマーを着用できず、レベルの進行が非常に遅いですが、ミサイル兵
器以外のすべてのスキルにはかなり優れています。それでも、各色には独自の強みがあ
り、いくつかの色には補完的な弱みがあるため、プレイヤー側に多少の柔軟性が必要に
なる場合があります。

レッド・ドラコニアン
  燃えるような環境でくつろいでください。氷の魔法は苦手ですが、火の扱いには非常
  に優れています。彼らの灼熱の息は炎の雲を残します。

ホワイト・ドラコニアン
  凍傷に侵された土地に由来しており、自然に霜に耐性があります。彼らの息は突き刺
  すように冷たい。氷魔法に精通しているが、火が苦手。

グリーン・ドラコニアン
  有毒な環境に慣れており、メフィットの蒸気の雲を吸います。彼らは特に毒の芸術に
  優れており、他の魔法の領域でも欠点がありません。その後、彼らは毒針を開発しま
  す。

イエロー・ドラコニアン
  腐食性の酸で満たされた硫黄の息を吐き、後に酸性の咬傷攻撃を受けます。耐酸性も
  あります。

グレイ・ドラコニアン
  彼らは呼吸武器を持っていませんが、生きるために呼吸する必要もないので、深海で
  も生き残ることができます。土魔法は得意だが空気魔法は苦手で、鱗も他のドラコニ
  アンより硬い。

ブラック・ドラコニアン
  巨大な放電を引き起こす可能性があり、自然に絶縁されています。空気魔法は得意だ
  が、土魔法は面倒に感じる。彼らの翼は最終的に大きくなり、生来のスキルと空気魔
  法を組み合わせることで継続的に飛行することができます。

まだらのドラコニアン
  火には多少弱いですが、氷には弱くありません。彼らは隣接する人々に粘着性の炎の
  塊を吐き出すことができます。

パープルドラコニアン
  一般にすべての呪文詠唱、特にヘクスとチャームに高度に適応しています。彼らは他
  のほとんどのドラコニアンよりも物事を呼び起こすのが少し上手です。彼らは、攻撃
  を受けた者の魔法を剥奪する解呪のエネルギーを吐き出すことができ、当然他のドラ
  コニアンよりも敵対的な魔法に対する耐性が高い。

ペイル・ドラコニアン
  空気と火の魔法に優れており、他の流派と比べても欠点がありません。彼らは蒸気を
  吐き、パープルのいとこと同様に、召喚においてわずかに有利です。

****************************************
2. ゲーム開始時の職業一覧
****************************************

クエストでは、あなたは多数の異なるタイプのキャラクターの1人としてプレイします。
それぞれに独自の長所と短所がありますが、少なくとも最初は、他のものよりも明らか
に簡単なものもあります。初心者にとって最適な職業はおそらく剣闘士とバーサーカー
です。本当にマジシャンをプレイしたい場合は、ConjurerまたはWizardを試してくださ
い。ただし、すべての種族がすべての職業に同様に適しているわけではありません。一
般に、選択画面上の明るい色の選択肢は、よりアクセスしやすいものであると考えられ
ます。

各職業は、最初はスキルとアイテムの異なるセットから始まりますが、そこから自由に
形を整えることができます。サイズや体型の特殊性により、一部のキャラクターは異な
る在庫から始まることに注意してください。

ファイターズ
  戦闘機は通常、優れた武器、重鎧、盾、および力のポーションを持って始まります。
  彼らは戦闘芸術において一般的な素養を持っています。

剣闘士
  剣闘士はリングで戦うために訓練を受けているため、格闘技には精通していますが、
  それ以外のことはあまり得意ではありません。実際、剣闘士はモンスターを重いもの
  で殴ること以外は何も学んでいません。彼らは厄介な武器、軽装鎧、頭装備、そして
  いくつかの網から始まります。

僧侶
  僧侶は、武道の鍛錬を通じて心身の完成を目指す修道会の会員です。モンクは非常に
  少ない装備で始まりますが、他の職業のキャラクターが必要とする重い武器や魔法の
  本がなくても生き残ることができます。初めて神を選択するとき、彼らの霊的訓練に
  より信仰値のブーストが与えられます。

バーサーカー
  バーサーカーは、怒り狂うトログを崇拝する屈強な戦士であり、怒り狂う力（価値が
  あることが証明されれば他の多くの力も同様に）を彼から得ますが、呪文魔法の使用
  を禁じています。彼らは自分で選んだ武器を持ち、動物の皮を着てダンジョンに入り
  ます。

カオスナイツ
  カオスナイトはXomのおもちゃです。 Xomは、気まぐれに応じて報酬を与えたり罰し
  たりする非常に予測不可能な(そしておそらく精神異常な)存在です。

アビサルナイツ
  アビサルナイトは、アビスの支配者であるアンフォームドのルゴヌに仕える戦士です。
  彼らはアビスに対してある程度の力を与えられており、その見返りに死と無秩序を広
  めなければなりません。

スカルド
  スカルドはそれ自体が恐るべき戦士であり、詠唱または歌唱する戦闘魔法を強化する
  形式を実践しています。これらの呪文と公式は、その起源となる高地に特有のもので
  あり、第二の天性のものです。それらは、自分自身とその同盟者に偉大さを鼓舞する
  ことも、敵の心に恐怖を与えることもできます。

ワーパー
  ワーパーは転移魔法を専門とし、長距離を移動して正確に位置を決める専門家であり、
  これを近接戦闘やミサイル戦闘で有利に利用します。それらは点滅のスクロールから
  始まります。

暗殺者
  アサシンは、短剣や吹き矢を使って殺すことに特に優れたステルスキャラクターです。
  彼らはいくつかの致命的なクラーレ針から始まります。

ハンター
  ハンターはミサイル兵器を専門とする戦闘機の一種です。ハンターは、いくつかの投
  擲武器または遠距離武器といくつかの弾薬、短刀またはこん棒、および革のセットを
  持って開始します。

秘術の射手
  Arcane Marksmanは、衰弱させる呪文を使用して遠距離攻撃を支援するハンターです。
  彼らは特に敵を遠ざけるのが得意です。

工匠
  工匠は、自ら魔法を唱えるのではなく、ガジェット、機構、難解なアイテムから引き
  出される魔法に慣れています。その結果、彼らはさまざまな杖を持ってダンジョンに
  入ります。工匠は魔法のアイテムを呼び出すことに熟練しており、近接戦闘の基本も
  理解しています。

放浪者
  放浪者とは、特定の職業を学んでいない人々のことです。その代わりに、彼らは「何
  でも屋で何のこともできない人」になって各地を旅してきました。彼らは、スキルの
  大量のランダムな品揃えと、おそらく途中で拾ったいくつかの小さなアイテムを使っ
  てゲームを開始しますが、それ以外は、ほぼ自分たちで行動します。

マジシャン
========================================

マジシャンは、それ自体が使用可能なキャラクター職業ではなく、ウィザード、コンジ
ュラー、エンチャンター、サモナー、ネクロマンサー、トランスミューター、さまざま
なエレメンタリスト、ヴェノムメイジを含む職業のタイプです。マジシャンは魔法を使
うのが最も得意です。とりわけ、彼らはローブと呪文の本から始まり、最初の数レベル
を通過することができます。

魔法使い
  ウィザードは、魔法のどの分野にも特化していない魔術師です。ウィザードは、さま
  ざまな魔法のスキルと暗記されたマジックダーツから始まります。彼らの本により、
  彼らは秘術のさまざまな分野で進歩することができます。

魔術師
  コンジュラーは、暴力的で破壊的な召喚魔法呪文を専門としています。ウィザードと
  同様に、コンジャラーはマジックダーツ呪文から始まります。

エンチャンター
  エンチャンターはヘックスの繊細な芸術を専門としています。敵に直接ダメージを与
  える代わりに、ヘックスは敵を無力化して衰弱させ、エンチャンターが戦闘で無力な
  クリーチャーにとどめを刺すことを可能にします。エンチャンターは、軽いエンチャ
  ントが施された武器と防具、およびコロナ呪文から始まります。

サモナー
  サモナーは、この世界と他の世界から生き物を呼び出して支援を与えることを専門と
  しています。最初は非常に弱虫な生き物しか召喚できませんが、より高度な召喚呪文
  を使用すると、召喚者はエレメンタルやデーモンなどの力を呼び出すことができます。

ネクロマンサー
  ネクロマンサーは、魔法のあまり楽しくない側面を専門とする魔術師です。死霊術呪
  文はさまざまですが、その多くは術者にある程度のリスクや危害を伴います。

トランスミューター
  トランスミューターは変性魔法を専門とし、自分自身や他人に奇妙な変化を引き起こ
  すことができます。彼らは主に素手格闘でダメージを与え、多くの場合、防御力と攻
  撃力を強化するために変換を使用します。

ヴェノムメイジ
  ヴェノムメイジは毒魔法を専門とし、毒魔法の影響を受けない生物がほとんどいない
  ダンジョンの浅いレベルでは非常に役立ちます。

エレメンタリスト
  エレメンタリストは、空気、火、土、氷の4種類の元素魔法のいずれかを専門とする
  魔術師です。

  火の魔法
    破壊的な妖術を中心とします。

  氷の魔法
    破壊的な妖術と防御的な加護術の両方を扱います。

  風の魔法
    独自の破壊的な力に加え、便利な加護術を数多く扱います。

  地の魔法
    破壊、防御、実用の各種呪文を幅広く扱います。

****************************************
3. スキル一覧
****************************************

ここでは、お持ちのスキルについて説明します。 'm'コマンドで現在のスキルを確認で
き、その中で'*'を使用して進捗表示と適性表示を切り替えることができます。適性表
はヘルプメニューから'?%'で、キャラクター選択中にも'%'で読むことができます。

スキルとの戦い
========================================

戦闘は白兵戦で使用される基本的なスキルであり、キャラクターがどの武器を使用して
いるかに関係なく適用されます(存在する場合)。戦闘もスキルであり、レベルが上がる
につれてキャラクターが獲得するヒットポイントの数を決定します(これは、高い戦闘
スキルから開始することで長期的に有利にならないように計算されることに注意してく
ださい)。特定の武器スキルとは異なり、戦闘によって攻撃の速度は変わりません。

武器スキルは、特定の近接武器で戦う能力に影響します。武器スキルには以下が含まれ
ます:

  * ショートブレード
  * ロングブレード
  * メイス＆フレイル
  * 軸
  * 五線譜
  * ポールアーム

あるクラスの武器、たとえばロングブレードの使用にすでに慣れている場合は、ショー
トブレードなどの同様の武器を使用するとボーナスが得られます。これはクロストレー
ニングと呼ばれ、スキルメニューでは青色で表示されます。同様の種類の武器は次のと
おりです。

  * ショートブレードとロングブレード
  * メイス＆フレイルと斧
  * ポールアームと斧
  * 杖と棒武器
  * ステーブとメイスとフレイル

特定の武器に優れていると、その武器で攻撃する速度が向上します。基本速度と可能な
最高(最低)速度の両方が武器のインベントリエントリに表示されます。軽い武器は素早
く正確に攻撃できるため、最初は使いやすいですが、重い武器は、スキルを向上させる
につれて、ダメージの可能性が急速に増加します。武器の現在の遅延を確認するには、
武器を空中で振り(Ctrlキーを押しながら)、ターンカウントの横にある括弧内の数字を
確認します。

一部の武器タイプには特殊な能力があります。斧は一振りで複数の敵を切り裂くことが
でき、攻撃のたびに使用者の周囲に弧を描いて敵を攻撃します。ポールアームはより遠
くまで届くことができ、使用者は2マス離れた相手を攻撃することができ、さらにはモ
ンスターを超えることもできます。 'v'コマンドを使用して特定のモンスターをリーチ
攻撃でターゲットにするか、オートファイト('tab')を使用して自動的にリーチします。

素手格闘は特殊格闘スキルです。これにより、キャラクターは非武装時に強力な攻撃を
行うことができ、追加の近接攻撃としてオフハンドでパンチすることもできます。素手
格闘は、重装甲や盾と組み合わせて使用するのが特に困難です。素手格闘スキルは、非
武装の間、攻撃速度が上げられなくなるまで攻撃速度を上げ続けます。

補助攻撃（Centaur's kick or a Minotaur'の頭突きなど）は素手格闘スキルの影響を
受けないことに注意してください。

遠距離戦闘スキル
========================================

ミサイル兵器には、個別の兵器スキルが多数あります。

  * 投擲（吹き矢含む）
  * 弓
  * クロスボウ
  * スリング

投擲は、ランチャーなしで投げられるすべてのもの(トマホーク、ジャベリン、トマホ
ーク、ネットなど)を表すスキルです。もう1つのスキルは、ランチャーで発射されるさ
まざまなタイプのミサイルを指します。例外は針です。これらは吹き矢を使用して発射
され、投擲スキルを使用するアクションです。ランチャーなしで石を投げても何らかの
効果が得られるため、これらのスキルは次のようにクロストレーニングします。

  * 投げとスリング

マジックスキル
========================================

呪文詠唱は魔法用の基本的なスキルです。戦闘がヒットポイントに影響するのと同じよ
うに、魔法のエネルギー (マジック)の蓄えに影響します。呪文詠唱スキルを増やすた
びに、いくらかのMPを獲得し、0.5で割り切れるスキルレベルに達するたびに、呪文レ
ベルを獲得します。このスキルは、詠唱による空腹感の量に大きく影響します。呪文詠
唱も呪文の威力と成功率を高めますが、より特化した魔法のスキルほどではありません。

さまざまなタイプの魔法ごとに個別のスキルもあります。スキルが高いほど、呪文はよ
り強力になります。学際的な呪文は、2つまたは3つのスキルの平均を使用します。

その他
========================================

鎧
  ボディアーマーが重いほど、損傷からより確実に保護されますが、いくつかの欠点が
  あります。

  高い鎧スキルを持っているということは、重い鎧を着ることに慣れていることを意味
  し、より自由に動き、より多くの保護を得ることができます。 (インベントリ内から
  )防具の説明を見ると、それがいかに面倒であるかが特にわかります。これは負担率
  によって測定されます。

  このスキルは、ボディアーマーの回避力ペナルティを克服するのに役立ち、重装甲が
  近接戦闘を妨げる量を減らし、また、呪文詠唱に対する重装甲の悪影響をいくらか軽
  減します。ハイアーマースキルは、他のタイプのアーマー (グローブ、マントなど)
  によって提供されるACも増加します。

回避
  高い回避率スキルは、近接攻撃や遠距離攻撃をより効果的に回避するのに役立ちます。
  これは軽い鎧の場合により簡単に実行できますが、重い鎧でも依然として役立ちます。

ステルス
  気付かれるのを避けるのに役立ち、モンスターが視線から離れたときにあなたを見失
  いやすくなります。重い鎧を着たり、邪魔されたりすると、ステルスの試みにペナル
  ティが課されます。大型の生き物（トロールなど）は、異常にステルス性の高いナー
  ガを除いて、ステルス性が苦手です。

  ステルスは、まだあなたに気づいていない眠っている/休んでいるモンスターに対し
  て非常に強力な先制攻撃を行うのにも役立ちます。これは短剣の場合に最も効果的で
  すが、他の短い刃の場合は若干効果が低く、長い刃、こん棒、槍、トライデント、ネ
  コ科の爪の場合は若干効果が低く、最後に、他の武器ではさらに効果が低くなります
  （それでも無視できるわけではありません）。

  ステルスは、混乱したり、気を散らしたり、無力化したモンスターに対する一部の近
  接攻撃も改善しますが、これは、モンスターが眠っている場合や麻痺している場合よ
  りもはるかに効果が低くなります。

  武器の種類によるボーナスに加えて、使用している武器のステルススキルとスキルの
  平均に基づいて追加の刺殺ボーナスがあることに注意してください。

シールド
  盾を使用することで得られる保護の量と、それが妨げる程度に影響します。ほとんど
  のレースでは、5/15/25スキルでそれぞれバックラー/シールド/ラージシールドの負
  担を軽減できますが、大規模なレースではスキルの必要性は少なく、小規模なレース
  では必要な量が多くなります。

呼び出し
  神に助けを求める能力に影響します。発動に熟練した者は失敗率を減らし、より強力
  な効果を生み出すことができます。一部の神(Trogなど)は、信者にこのスキルを学習
  させる必要はありません。

召喚
  このスキルを使用すると、ダメージと精度の両方の点で杖をより効果的に使用できる
  ようになります。さらに、高い召喚を使用すると、使用を通じて杖のチャージ数を簡
  単に推測できます。同様に、特定の力を持つ他のすべてのアイテム(水晶玉、カード
  のデッキ、またはエレメンタルサモナーなど)は、このスキルで訓練されたキャラク
  ターにとってより適切に機能します。

  InvocationsとEvocationsは最大魔法の蓄えを増やすことができますが、この点では
  どちらも呪文詠唱よりも効果が小さくなります。ボーナスは累積されません。呪文詠
  唱、InvocationsまたはEvocationsからの最も高い寄与が使用されます。

****************************************
4. コマンド詳細一覧
****************************************

メイン画面
========================================

Crawlには、単一のキーストロークで発行できるコマンドが多数あります。いくつかの
モードがあるため、これは混乱を招く可能性があります。ここに完全なリストがありま
す。一部のコマンドは、特定のインターフェイスオプションと組み合わせると特に便利
です。そのようなオプションはリストに記載されています。それらの説明については、
options_guide.txtをご覧ください。すべてのコマンドのより簡潔なリストについては、
ゲーム内で'??'を使用してください。ほとんどのモード(ターゲティング、レベルマッ
プ、レベル間移動)には、独自の'?'経由のヘルプメニューもあります。

動き
----------------------------------------

方向
  これで1マス移動します。方向は、テンキーのカーソルキーのいずれか(Numlockのオ
  ンとオフの両方を試してください)、またはRogue viキーのいずれか(hjklyubn)です。

Shift-directionまたは/方向
  これは、興味深いものが見つかるまで真っ直ぐに進みます(モンスターなど)。最初の
  マス目が罠の場合でも移動は開始されます。

o
  自動探索。オプションexplore_greedyをtrueに設定すると、興味深いアイテム(自動
  的に取得されるアイテム)または山(内容の確認)に対して自動探索が実行されます。
  travel_open_doorsをfalseに設定した場合を除き、自動探索は自動的にドアを開きま
  す。

GまたはCtrl-G
  レベル間の自動移動(任意の階層または中継地点へ)。中断された場合
  でも古い目的地を記憶します。このコマンドには独自のショートカットセットがあり
  ます。使用？彼らの助けを求めて。

Ctrl-W
  中継地点(0～9の数字)を設定します。show_waypointsオプションも参照してくださ
  い。Ctrl-GまたはGに続けて数字を押すと、中継地点へ自動移動できます。

休憩中
----------------------------------------

s、デル、。またはテンキー 5
  1ターン休みます。これは、数ターン待つために戦術的に使用されることが最も多い
  です。キーボードと正気の状態を保つために、本格的な休息は5コマンドで行う必要
  があります。

5またはShift-Numpad 5
  体力とMPが両方とも満タンになるか、100ターンが終了するまで、長い休憩をとりま
  す。

休息はマンティコアのスパイクを取り除く唯一の方法ですが、それ以外の場合は他の行
動と区別がつきません。回復やマジックポイントの回復などは、休んでいてもいなくて
も同じ速度で進みます。

ダンジョンインタラクション
----------------------------------------

O
  ドアを開けてください。これもドアに入ると自動的に行われます。

C
  ドアを閉めてください。

Ctrl-directionまたは*方向
  指定されたマス目の既知のトラップを解除しようとします。そうでない場合は、ドア
  がある場合は開閉し、そうでない場合は移動せずに攻撃します(モンスターが表示さ
  れない場合でも)。

<
  階段を使って上へ行くか、ショップやポータルに入ります。

>
  階段を使用して奥に進むか、ショップやポータルに入ります。

;
  占有タイルと自動ピックアップ対象アイテムを調べます。同じマス上に他のアイテム
  がない状態でスタックの一部だけを拾うのにも使用できます。

x
  周囲を調べてください。以下を参照してください。 '?'のヘルプがあります。

X
  レベルマップを調べてください。以下を参照してください。 '?'のヘルプがあります。

Ctrl-X
  表示されているすべてのモンスター、アイテム、機能をリストします。説明を読んで、
  項目または機能に移動することができます。

Ctrl-O
  ダンジョンの概要（支店、店舗など）を表示します。

!
  現在のレベルに注釈を付けます。任意のテキストを入力できます。この注釈はダンジ
  ョン概要(Ctrl-O)にリストされ、またそのレベルに再度入るたびに表示されます。階
  段に立っているときにこのコマンドを使用すると、階段が続くレベルに注釈を付ける
  こともできます。注釈に感嘆符(!)が含まれている場合は、レベルに入る前にプロン
  プトが表示されます。空の文字列を指定すると、注釈がクリアされます。

キャラクター情報
--------------------------------------

以下の'display'はメッセージ領域の使用を意味し、'show'は画面全体の使用を意味し
ます。

@
  キャラクターのステータスを表示します。

[
  着用した鎧を展示します。

}
        集めたルーンの一覧を表示します。

"
  着用済みのジュエリーを展示します。

E
  体験情報を表示します。

^
  宗教画面を表示します。

A
  能力を表示/変異。

a
  能力を選択するか、その説明を読んでください。え？または*は現在の能力をメニュ
  ーとして表示します。

\\
  アイテム知識を表示します。この画面では、項目タイプの自動ピックアップ例外を切
  り替えることができます。画面には独自のヘルプテキストがあります。

m
  スキル画面を表示します。その画面から現在のスキルの説明と適性を取得できます。
  画面には独自のヘルプテキストがあります。

i
  在庫リストを表示します。このリスト内でスロットキーを押すと、その項目に関する
  情報が表示されます。

]
  着用、使用、震えているアイテムのみを含む、制限された在庫を表示します。

I
  記憶されている呪文のリストを表示します。

%
  耐性と一般的なキャラクターの概要を表示します:健康、経験、お金、装備、ステー
  タス、変異、能力(後の3つはコマンド@、A、aを使用する場合よりも簡潔です)。 [、
  "、E、^、@、A、a、$を一画面に凝縮したものです。表示された項目のキーを押すと
  表示されます。

その他のゲームプレイコマンド
----------------------------------------

a
  特別な能力を使用します。

p
  通常、何らかのアイテムを犠牲にするために神に祈ります。

z
  呪文をキャストします。呪文がターゲットとしてモンスターを要求しているにもかか
  わらず、範囲内にターゲットが存在しない場合、キャストは停止されます。この場合、
  ターンも魔法も使用しません。それでも呪文をキャストしたい場合は、Zを使用して
  ください。

Z
  範囲制限に関係なく、呪文をキャストします。

t
  味方に命令を伝えたり、叫んだり（tt付き）。

Ctrl-A
  自動ピックアップを切り替えます。目に見えないモンスターに遭遇すると、常に自動
  ピックアップがオフになることに注意してください。その後、Ctrl-Aでスイッチをオ
  ンにする必要があります。

Ctrl-V
  残りのHPに応じてモンスターの色を切り替えます。 (コンソールのみ)

Ctrl-T
  モンスター' weapons'グリフの表示を切り替えます。 (コンソールのみ)

\`
  前のコマンドをやり直す

0
  次のコマンドを指定された回数繰り返します

ゲームプレイ以外のコマンド
----------------------------------------

?
  ヘルプメニュー。

Ctrl-P
  以前のメッセージを表示します。

Ctrl-R
  画面を再描画します。

Ctrl-C
  メインマップとレベルマップをクリアします。

#
  文字をファイルにダンプします(name.txt)。

:
  ダンプファイルにメモを追加します(オプションtake_notesを参照)。

?:
  ゲーム内の注意事項を読んでください。

?V
  バージョン情報を表示します。

?/
  モンスター、呪文または機能について説明します。完全な名前の代わりに、名前の一
  部または正規表現を入力できます。

~またはCtrl-D
  マクロとキーマッピングを追加または保存します。

=
  インベントリ/呪文/能力文字を再割り当てします。

_ (コンソール)またはF12 (WebTiles)
  メッセージを読みます(オンラインでプレイしている場合。ローカルゲームではあり
  ません)。

\-
  プレイヤー人形を編集します(タイルのみ)。

ゲームの保存
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

S
  クエリを指定してゲームを保存し、終了します。

Ctrl-S
  クエリを実行せずにゲームを保存して終了します。

Ctrl-Q
  保存せずに終了します(前に尋ねられました)。

隠し場所
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Ctrl-F
  探す。これは隠し場所やショップを検索します。正規表現のほか、'long blades'、'
  shop'、'altar'、'artefact'などの用語も使用できます。特別な神の祭壇を探してい
  る場合は、 'Trog'などで検索すると機能します。 'D:13'のような文字列は、そのレ
  ベルの既知のアイテムをすべてリストします。 'D:1}'は、D:10からD:19までのアイ
  テムもリストする'D:1'とは対照的に、レベル1のアイテムのみを検索します。見つか
  ったすべての場所のリストが表示されたら、そこに自動移動する(関連する文字を押
  す)か、アイテムを調べる(?の後に文字を押す)ことができます。

アイテムインタラクション（インベントリ）
========================================

{
  項目を書き込みます(自動書き込みオプションをチェックします)。空の碑文または碑
  文のみのスペースは、以前の碑文を削除します。付録
  `6. アイテムへの銘の効果`_を参照して
  ください。また、インベントリ内のスロットキーを押してアイテムを表示するときに、
  アイテムを刻印することもできます。

f
  震えるミサイルを発射。いくつかのモンスターが視界内にある場合、最後のターゲッ
  トまたは最も近いモンスターが自動的にターゲットになります。もう一度fを押すと
  撮影されます。

F
  アイテムを直接選択して発射します。 fiとは異なり、これは矢筒を変更しません。

（そして）
  それぞれ次/前の適切なミサイルに矢筒を切り替えます。

Q
  メニューの矢筒アイテム。

q
  ポーションを飲みます。

e
  食べ物を食べます（最初にフロアを試し、次に在庫を試します）。食事プロンプトで
  は、eはyと同義です。

r
  巻物や本を読みます。本を読んでいるとき、呪文を忘れるために本を破壊することが
  あります。

M
  本の呪文を暗記します。

w
  アイテムを使用します(なしの場合は-)。

'
  アイテムaを装備するか、bに切り替えます。

v
  装備したアイテムの力を呼び起こします。隣接していないモンスターをポールアーム
  で攻撃するためにも使用されます。

V
  インベントリからアイテムを呼び出します。これには杖の使用も含まれます。

W
  鎧を着てください。

T
  鎧を脱いでください。

P
  ジュエリーを身につけてください。

R
  宝石類を外してください。

アイテムインタラクション（フロア）
========================================

g or ,
  アイテムを拾います。少量の商品を受け取る場合はプレフィックスを使用してくださ
  い。ドロップと同様に、Ctrl-Fを使用すると、正規表現に一致する項目を選択できま
  す。

d
  アイテムをドロップします。ドロップリスト内で、Ctrl-Fを押してから正規表現を押
  すと、正規表現に基づいてスロットを選択できます。

d#
  正確な数の項目をドロップします(#は数字です)。

D
  最後に拾ったアイテムをドロップします。

c
  死体を切り刻みます。地面に複数の死体がある場合は、1つずつプロンプトが表示さ
  れます。そこで、答えられます

  =========  ========================================
  y, c       はい（この死体を解体する）
  n, Space   いいえ（この死体を飛ばす）
  a          すべてはい（すべての死体を解体する）
  q, Esc     解体を中止する
  =========  ========================================

リスト内のショートカット(マルチドロップなど)
========================================

ドロップするとき、ドロップメニューはいくつかのショートカットを受け入れます。ピ
ックアップメニューも同様です。以下では、項目がすでに選択されている場合、キーを
押すとその選択が解除されます(','と'-'は当然除きます)。

(
  すべてのミサイルを選択します。

)
  すべての手持ち武器を選択します。

[
  すべての防具を選択します。

?
  すべてのスクロールを選択します。

%
  すべての食品を選択します。

&
  すべての腐肉と食べられない食べ物を選択してください。

\+ or :
  すべての本を選択します。

/
  すべての杖を選択します。

|
  すべての五線を選択します。

\\
  すべてのロッドを選択します。

!
  すべてのポーションを選択します。

=
  すべてのリングを選択します。

"
  すべてのアミュレットを選択します。

}
        その他の項目をすべて選択します。

,
  グローバル選択(drop_filterオプションの対象)。

\-
  グローバル選択解除(drop_filterオプションの対象)。

\*
  選択を反転します。これにより、drop_filterオプションを使用する場合でも、すべ
  ての項目を選択できるようになります。

.
  次の項目を選択します。 (リスト内の項目のキーを押した場合、'.'は次の項目を切
  り替えます。これを繰り返して、後続のいくつかの項目をすばやく選択できます)。

レベルマップ('X')
========================================

レベルマップ(メイン画面で'X'によって表示される)は、画面全体を使用してダンジョ
ンを表示します。通常、その画面の最初の行にはレベルの名前とヘルプ画面のヒントが
表示されます。 level_map_titleオプションを使用すると、これを取り除くことができ
ます。

Esc、スペース
  レベルマップを残します。

?
  レベルマップのヘルプ。

\-
  レベルマップを上にスクロールします。

\+
  レベルマップを下にスクロールします。

方向
  カーソルを移動します。

Shift-direction
  カーソルをより大きなステップで移動します(オプションまたは/方向
  level_map_cursor_stepを確認してください)。

.
  カーソルに移動します(Enter、Del、','、';'も)。カーソルがキャラクター上にある
  場合は、代わりに最後の移動目的地にカーソルを移動します。

<
  上り階段を順繰りに選択します。

>
  下り階段を順繰りに選択します。

^
  罠を順繰りに選択します。

_
  祭壇を順繰りに選択します。

タブ
  店やポータルを順繰りに選択します。

I
  すべてのアイテムを順に選択します。

O
  すべてのアイテムを逆順に選択します。

Ctrl-C
  レベルとメインマップをクリアします(一時的に見えるモンスター、雲などから)。

Ctrl-F
  レベルマップのことは忘れてください。

レベルマップ上には中継地点を設定でき、Gでそこへ自動移動できます。
show_waypointsオプションも参照してください。コマンドは次のとおりです。

Ctrl-W
  中継地点を設定します。

W
  この階層のすべての中継地点を順繰りに選択します。

自動移動禁止指定では、マップ上の場所を自動移動と自動探索の立ち入り禁止エリアに
できます。

e
  自動移動禁止エリアを設定します。すでに設定されている場合は、範囲を1マスから視
  界全体へ変更し、さらに実行すると設定を解除します。

Ctrl-E
  この階層の自動移動禁止エリアをすべて除去します。

E
  自動移動禁止エリアを順繰りに選択します。

周囲の調査('x')
========================================

ダンジョン内で'x'を押すと周囲の調査モードになり、視界内のアイテムやモンスター
を調べられます。

Esc、スペース、x
  プレイ画面に戻ります。

?
  特別なヘルプ画面。

\* or '
  アイテムを順に選択します。

/ or ;
  アイテムを逆順に選択します。

\+ or =
  モンスターを順に選択します。

\-
  モンスターを逆順に選択します。

方向
  カーソルを移動します。

. または Enter
  カーソル位置まで自動移動します(Delも同様)。

v
  カーソル下の地形またはモンスターを説明します。一部の分岐入口には特別な情
  報が含まれています。

>
  下り階段を順繰りに選択します。

<
  上り階段を順繰りに選択します。

_
  祭壇を順繰りに選択します。

タブ
  店やポータルを順繰りに選択します。

ターゲティング
========================================

ターゲティングモードは周囲を調べるのと似ています。これは、発射物を発射したり、
杖を呼び出したり、ターゲットを使用する呪文をキャストしたりするたびにアクティブ
になります。 Space (起動)を除いて、周囲の調査について説明したすべてのコマンド
が機能します。

Escまたはx
  ターゲットを絞るのはやめましょう。

?
  特別なヘルプ画面。

入力
  カーソル方向に発射します(DelとSpaceも同様)。

.
  カーソル位置で発射し、衝撃をわずかに軽減してそこで停止します。これは、ペット
  の損傷を避けたり、矢を紛失したりするのを防ぐのに役立ちます。

p
  前のターゲットに発砲します(まだ視界にある場合)。

f
  スマート射撃:前の目標がまだ視界にある場合は、その目標に向かって射撃します。
  それ以外の場合はカーソル位置へ射撃します。'ff'で敵への射撃を始め、その後も
  'ff'で射撃を続けることができます。

:
  ビームパスの表示を切り替えます。

（そして）
  これら2つのコマンドを使用すると、ターゲティング中に弾薬を変更できます。選択
  は、fire_orderオプションの影響を受けます。通常、発射装置に応じてミサイルを変
  更します。つまり、弓を振るうとき、(と)はインベントリ内のすべての矢のスタック
  を順に切り替えます。

Shift-direction
  その方向に真っ直ぐ発射してください。

****************************************
5. ステータス表記一覧
****************************************

統計エリアには、現在楽しんでいるエンチャント、または苦しむ必要があるエンチャン
トを表示するためのスペースがあります。これらのエンチャントのリストは次のとおり
です。一部は省略されているか、特殊な効果を持っている場合があります。

（ほとんど）良いエンチャント
========================================

満杯
  たくさん食べましたね。

とてもいっぱい
  とりあえず食べられるものはほぼ全部食べましたね。

興奮した
  今のところこれ以上食べることはできません。

速い
  すべてのアクションが50%速くなります。これは時間の経過とともに魔法の汚染を引
  き起こし、このステータスを取得する前にすでに汚染されていた場合は危険なレベル
  の汚染を引き起こす可能性があります。

インビス
  あなたは目に見えない存在です。ほとんどの敵はあなたを見つけることができず、攻
  撃するとペナルティを受けますが、あなたの大まかな位置を推測できる場合がありま
  す。 Invisは時間の経過とともに魔法の汚染を引き起こし、このステータスを取得す
  る前にすでに汚染されていた場合は危険なレベルの汚染を引き起こす可能性がありま
  す。この効果がグレー表示されている場合は、アクティブです(汚染を引き起こしま
  す)が、何らかの理由で効果がありません(例:あなたが輝いている、天使の光輪が点
  灯しているなど)。

テレ
  あなたはテレポートしようとしています、つまり「不安定」に感じています。テレポ
  ートしようとしている場合、テレを適用する別の効果(スクロール、ワンドなど)によ
  ってテレポートがキャンセルされます。

cテレ
  次に行う移動は、半制御(瞬きの場合)または完全制御(テレポートの場合)になります。
  制御されたテレポートであっても完全に信頼できるわけではないことに注意してくだ
  さい。選択した目的地の近くに着地する可能性が高く、壁の内側に着地する場合は完
  全にランダムな場所に着地する可能性があります。

飛行
  地上を飛行し、ペナルティなしで水や溶岩を渡ったり、浅瀬の上で戦ったりできます。
  ほとんどの飛行効果には制限時間があるため、効果が切れるときに危険な液体の上に
  いないよう注意してください。

アギ
  あなたは不自然に機敏です。これにより、器用さ、回避力、およびステルスにボーナ
  スが与えられます。

ブリル
  あなたは不自然に賢いです。これにより、知力、呪文詠唱の成功とスペルパワーにボ
  ーナスが与えられます。

かもしれない
  あなたは不自然に強いです。これにより、腕力と物理戦闘でのダメージにボーナスが
  与えられます。

リジェネ
  異常に速い速度でヒットポイントを再生成します。これは一時的な再生の場合にのみ
  表示されます。

RMsl
  ミサイルを撃退します。つまり、ミサイルを回避する可能性が十分にあります。この
  効果は、呪文によって提供される場合、弾かれるすべての発射物によって期限切れに
  なる可能性があります。それ以外の場合は無期限に続きます。

DMsl
  ミサイルをそらします。つまり、ミサイルを回避する大きなチャンスがあります。こ
  の効果は、呪文によって提供される場合、発射物が反射されるたびに期限切れになる
  可能性があります。それ以外の場合は無期限に続きます。

触る
  非武装の攻撃はダメージを与えなくなりましたが、命中したときにモンスターを混乱
  させる可能性があります。

MR
  敵対的な魔法に対する耐性が高くなります。

ベルセルク
  あなたはより強く、より速く、よりタフに！ただし、モンスターを殺さないとこのス
  テータスはさらに早く減り、減った場合は動きが鈍くなり疲れ果て、一時的に気を失
  ってしまう可能性があることに注意してください。

（ほとんどが）悪いエンチャント
========================================

お腹がすいた
  ほとんどの種族は空腹の場合にのみ死体の塊を食べることができます。

とてもお腹が空いた
  いつもよりさらにお腹が空いています。

飢餓に近い
  あなたは食べ物がどうしても必要です。

飢えている
  本当に何か食べるべきです。死は遠くない。飢えている間は戦闘能力が低下し、呪文
  を唱えたり、多くの誘発能力や神聖な能力を使用したりすることができなくなります。

ポワ
  あなたは毒に侵され、ヒットポイントを失い続けます。毒を受けている間、現在の健
  康状態は部分的に色が変更され、最終的に与えられる毒ダメージが表示されます。治
  癒のポーションを使用するか、それが終わるのを待つことで治癒します。

会議
  あなたは混乱しています。アクションが適切に機能しなかったり、ランダムな方向に
  ターゲットが設定される可能性があります。呪文詠唱やスクロール使用は全く不可能
  です。そのまま待つか、治癒のポーションを飲んですぐに症状を和らげてください。

コンタム
  あなたは突然変異誘発性の放射線で輝きます。これは時間の経過とともにあなたを変
  異させる可能性があり、通常は悪い結果をもたらします。色は重大度を示します。最
  初のレベル(ダークグレー)は単なる警告であり、それによって変異やステルスの喪失
  は発生しません。

ドレイン
  あなたのスキルは負のエネルギーによって消耗されており、効果が低下しています。
  このステータスは待っていても消えませんが、経験を積むと期限切れになります。こ
  のステータスには複数のレベルがあり、スキルの画面を見るとどれだけ消耗している
  かがわかります。

呼吸
  一部の能力（ブレス武器やジンの詠唱の発動など）では、使用の合間に息を整える必
  要があります。これらの能力はブレス状態が消えるまで再使用できません。

エクス
  あなたは疲れ果てていて、特定の疲れる能力を使うことができません。特にベルセル
  ク。

遅い
  すべてのアクションにかかる時間が50%長くなります。

パラ
  あなたは麻痺しており、完全に行動することができません。

寝る
  あなたは眠っていて、まったく行動することができません。攻撃すると目が覚めてし
  まいます。

開催
  あなたは網か蜘蛛の巣に捕らわれています。あなたは自由に動くことができず、代わ
  りに自由にもがこうとします。

コンストラ
  敵に拘束されており、ターンごとに受けるダメージが増加します。また、敵から遠ざ
  かる動き（瞬きを含む）は制限されていますが、逃げるのに苦労する可能性があり、
  何度も逃げることで成功する可能性が高くなります。

メズム
  あなたは魅了され、魅了されているモンスターから離れることができません。

恐れ
  あなたは恐怖に圧倒され、恐怖を引き起こしているモンスターに向かって進むことが
  できません。

-cテレ
  このステータスがある場合はcTeleステータスを取得できない可能性があり、制御さ
  れた点滅を提供するエフェクト(呪文やスクロールなど)は信頼できません。

-テレ
  何らかの影響により、テレポートや瞬きができなくなります。

マーク
  罠や呪文の効果により、モンスターはより正確にあなたを追い詰めるようになり、あ
  なたが視界に入っていない場合でも検出できるようになります。

火
  あなたは粘着性の炎で覆われており、次の数ターンにわたってダメージを与えます。
  水に入ると火が消えます。

コロナ
  あなたは光に囲まれています。これによりステルス性が損なわれ、攻撃されやすくな
  ります。

バーブ
  皮膚には危険な棘が埋め込まれており、動き回るとダメージを受けます。数ターンそ
  の場に立ったり、動き回ったりすると消えます。

病気
  あなたは何らかの敵対的な影響によって病気になっています。ヒットポイントは治癒
  するまで回復しません(待つか、治癒のポーションを飲み干す)。場合によっては、主
  属性がドロップされることがあります。

腐った
  これは非常に有害な死霊病です。時間の経過とともに最大ヒットポイントが失われま
  す。一度失われたこれらを回復できるのは、回復薬と杖(および特定の能力)だけです。
  腐った状態自体は治癒のポーションを使用するか、それが終わるのを待つことで治癒
  します。

コル
  あなたの機器は有毒な酸で覆われています!物理的な戦闘と防御(AC)の両方の有効性
  が低下します。表示されている数字は前者を示します。一定時間が経過すると効果は
  消えます。

フレイ
  あなたは幻想に覆われていますが、それでも致命的です。 -傷。幻想の源を破壊する
  と、'flayed'離れていた健康状態が回復します。

弱い
  物理攻撃によるダメージは少なくなります。

ルーツ
  あなたは生き生きとした根によって地面に固定されています。移動速度が遅くなり、
  回避力が減少し、飛行できなくなります。

凍った
  氷に覆われ、移動速度が低下します。

樹液
  何らかの悪魔の力があなたの呪文詠唱を阻害しています。このステータスが有効な間
  に呪文をキャストするたびに、より多くの呪文をキャストできる可能性が低くなりま
  す。強力な呪文をキャストすると、弱い呪文をキャストするよりも成功の可能性が低
  くなります。

頭が悪い、不器用、崩壊
  あなたの属性の1つ(それぞれ、知力、器用さ、または腕力)が0になりました。特定の
  属性に関連するほとんどのアクションに対して、極度のペナルティが課せられます。
  属性を0より大きくすると、数ターンでステータスが消滅します。

さまざまな呪文にはさらにいくつかのエンチャントメッセージがあります。これらにつ
いては、エンチャントを引き起こす呪文の説明で説明されています。

****************************************
6. アイテムへの銘の効果
****************************************

{コマンドを使用して項目を手動で刻印できます。あるいは、インベントリからアイテ
ムを表示するときに刻印することもできます(アイテムの文字を押して行います)。これ
により、中括弧内の注記が項目の説明に追加されます。単にアイテムについてコメント
できるようにするだけでなく、さらにいくつかの用途があります。

自動刻印
========================================

これらは、アイテムを識別しやすくするためにゲームによって行われます。たとえば、
モンスターが使用しているのを見たアイテムには、「{モンスターが試した}」と刻まれ
ます。

ショートカットとしての碑文
========================================

実際の目録レターに関係なく、碑文を使用してアイテムに簡単にアクセスできるショー
トカットを定義できます。たとえば、アイテムの碑文に「@w9」が含まれている場合、
それを使用するには'w9'と入力できます。 9の代わりに、他の数字も同様に機能します。
また、'w'ieldの代わりに、アイテムの処理に使用される他のコマンド('e'at、'r'ead、
'q'uaff、e'v'oke、'f'ireなど)を使用できます。「@*9」を使用すると、'9'が続くア
クションコマンドでこれが使用されます。アイテム。

安全上の表記
========================================

次の文字列を含む碑文は、一部のコマンドの動作に影響を与えます。

!*
  このアイテムを使用するアクションの前にプロンプトを表示します。

!w
  このアイテムを使用したり使用を解除したりする前にプロンプトを表示します。

!a
  このアイテムを使用すると、攻撃する前にプロンプトが表示されます。非武器と遠距
  離武器は自動的にプロンプトを表示します。また、'y'と答えると、武器を切り替え
  るまで再度プロンプトが表示されません。

!d
  このアイテムをドロップする前にプロンプトを表示します。

!e
  この商品を食べる前に確認してください。

!q
  このアイテムを飲み込む前にプロンプトを表示します。

!r
  この項目を読む前にプロンプトを表示します。

!f
  このアイテムを発射または投げる前にプロンプトを表示します。

!W
  この鎧を着る前に確認してください。

!T
  この鎧を脱ぐ前にプロンプトを表示してください。

!P
  このジュエリーを着用する前に確認してください。

!R
  このジュエリーを取り外す前に確認してください。

!v
  このアイテムを呼び出す前にプロンプトを表示します。

!Q
  このアイテムを明示的に震える前にプロンプトを表示します。

!p
  この碑文を持つアイテムを含むスタックを犠牲にする前にプロンプトを表示します。
  答えが「いいえ」の場合、スタック全体がスキップされ、アイテムは犠牲になりませ
  ん。

=p
  この特定のアイテムを犠牲にする前にプロンプトを表示します。答えが「いいえ」の
  場合、Crawlはスタック内のさらにアイテムを犠牲にし続けます。

=g
  自動ピックアップがオンになっている場合、このアイテムは自動的にピックアップさ
  れます。

=f
  このアイテムを矢筒の自動選択から除外します。

\+f
  このアイテムを矢筒の自動選択に含めます。

=F
  射撃や投擲に使う矢弾を順に選ぶ際、このアイテムを除外します。

\+F
  射撃や投擲に使う矢弾を順に選ぶ際、このアイテムを含めます。

=R
  別のリングを取り外せる場合は、このリングの交換を申し出ないでください。

!D
  このアイテムを破壊する可能性のあるアクションを実行する前にプロンプトを表示し
  ます。このように刻まれたアイテムを犠牲にしたり、武器を破壊したり、さまざまな
  神の名で本を燃やしたりして破壊しようとしている場合、ゲームは確認を求めること
  さえせず、このアイテムを黙って無視します。また、お気に入りの武器に誤って
  Stick to Snakeをキャストすることも防ぎます。ただし、溶岩の事故や空腹のゼリー
  からは保護されません。

自動刻印オプションを使用すると、一部のアイテムを自動的に刻印することができます。
詳細については、「options_guide.txt」を参照してください。いくつかの例は次のと
おりです。

  autoinscribe = royal jelly:=g
  autoinscribe = wand of heal wounds:!v

アーティファクト自動刻印
========================================

多くのプレイヤーは、アーティファクトのプロパティの碑文を使用します。これにより、
インベントリや隠し場所の閲覧が容易になります。 Crawlは、自動碑文のスキームを提
供します。

ここでは、限られた行の長さを有効に活用するための簡潔さと、読みやすくするための
冗長性という2つの同時目標の間で交渉する必要があります。デフォルトの碑文では、
次の一般的な考え方が使用されます。

rXXX
  抵抗を意味します

\+XXX
  'a'コマンドで呼び出せる能力を意味します

\-XXX
  抑制された能力を意味します

XX+6
  数値ステータスのブーストを意味します(XX-2などと同様)

完全なリストは次のとおりです。

rC+
  1レベルの耐寒性

rC++
  2段階の耐寒性

rC-
  1段階の寒さのしやすさ

rF+
  1レベルの耐火性

rF++
  2レベルの耐火性

rF-
  1レベルの火災感受性

rN+
  1レベルの負のエネルギー耐性（生命保護）

MR++
  2レベルの魔法耐性(敵対的な魔法に対する耐性)

rポワ
  毒耐性

レック
  電気抵抗（絶縁）

AC+3
  AC (アーマークラス)モディファイア

EV+3
  EV (回避力)修飾子

強+3
  腕力修飾子

デックス+3
  器用さ修飾子

整数+3
  知力修飾子

スレイ+3
  精度とダメージの修正(近接戦闘および遠距離戦闘用)

ステルス+
  ステルスブースト

ステルス-
  ステルスペナルティ

rCorr
  腐食に耐える

rMut
  変異に抵抗する

\+フライ
  飛行のために呼び起こすことができます（'a'bilitiesメニューから）

\+Inv
  不可視状態を呼び起こすことができます('a'bilitiesメニューから)

\+まばたき
  まばたきを誘発することができます('a'bilitiesメニューから)

\+激怒
  狂戦士を呼び起こすことができます（'a'bilitiesメニューから）

\*激怒
  制御不能な狂暴性（近接攻撃で誘発される可能性があります）

\*テレ
  ランダムテレポーテーション

\-テレ
  テレポートを防ぐ

\-キャスト
  呪文詠唱を防止します

コンタム
  装備していない場合、高い魔法汚染を引き起こす

うるさい
  ヒット時に異音がする

呪い
  装備すると自身を呪う確率

火
  rF+、rC-、火の魔法を強化し、氷の魔法を弱める

氷
  rC+、rF-、氷魔法を強化し、火魔法を弱める

サストアブ
  持続能力

リジェネ
  再生

ウィズ
  魔術師

MP+3
  魔力補正

HP+3
  ヒットポイント修飾子

+cテレ
  一時的なテレポート制御を呼び出すことができます('a'bilitiesメニューから)

SInv
  目に見えないものを見る

クラー
  明瞭さ

グルメ
  美食家

区
  防御

精神
  守護霊

イナック
  不正確さ（失敗する可能性のあるすべての攻撃に影響します）

デバッグ碑文
========================================

ウィザードモードに入っている場合は、杖に'range:number' (例: 'range:50')を記述
することで、杖のザッピング範囲を変更できます。これは、プレイヤーがザップしたワ
ンドに対してのみ機能します。
